// Nel file src/services/TS formula1Data.ts
import { Season, Team, Driver, Circuit, TeamStand, DriverStand, Race, RaceDetail } from '../src/types';

export const seasons: Season[] = [
    { year: 2023 },
    { year: 2022 },
];


 

export const teams: Team[] = [
    { id: 1, name: 'Ferrari', country: 'Italy', engine: 'Ferrari En.' },
    { id: 2, name: 'Alfa Romeo', country: 'Switzerland', engine: 'Ferrari En.' },
    { id: 3, name: 'Haas', country: 'United States', engine: 'Ferrari En.' },
    { id: 4, name: 'Mercedes', country: 'United Kingdom', engine: 'Mercedes En.' },
    { id: 5, name: 'Aston Martin', country: 'United Kingdom', engine: 'Mercedes En.' },
    { id: 6, name: 'McLaren', country: 'United Kingdom', engine: 'Mercedes En.' },
    { id: 7, name: 'Williams', country: 'United Kingdom', engine: 'Mercedes En.' },
    { id: 8, name: 'Red Bull', country: 'United Kingdom', engine: 'Honda En.' },
    { id: 9, name: 'Alpha Tauri', country: 'Italy', engine: 'Honda En.' },
    { id: 10, name: 'Alpine', country: 'United Kingdom', engine: 'Renault En.' },
];

export const drivers: Driver[] = [
    { id: 1, name: 'Lando Norris', board_name: 'NOR', number: '4', country: 'United Kingdom', date_born: '1999-11-13' },
    { id: 2, name: 'Sergio Perez', board_name: 'PER', number: '11', country: 'Mexico', date_born: '1990-01-26' },
    { id: 3, name: 'Fernando Alonso', board_name: 'ALO', number: '14', country: 'Spain', date_born: '1981-07-29' },
    { id: 4, name: 'Lewis Hamilton', board_name: 'HAM', number: '44', country: 'United Kingdom', date_born: '1985-01-07' },
    { id: 5, name: 'Carlos Sainz', board_name: 'SAI', number: '55', country: 'Spain', date_born: '1994-09-01' },
    { id: 6, name: 'Lance Stroll', board_name: 'STR', number: '18', country: 'Canada', date_born: '1998-10-29' },
    { id: 7, name: 'George Russell', board_name: 'RUS', number: '63', country: 'United Kingdom', date_born: '1998-02-15' },
    { id: 8, name: 'Nico Hulkenberg', board_name: 'HUL', number: '27', country: 'Germany', date_born: '1987-08-19' },
    { id: 9, name: 'Charles Leclerc', board_name: 'LEC', number: '16', country: 'Monaco', date_born: '1997-10-16' },
    { id: 10, name: 'Valtteri Bottas', board_name: 'BOT', number: '77', country: 'Finland', date_born: '1989-08-28' },
    { id: 11, name: 'Esteban Ocon', board_name: 'OCO', number: '31', country: 'France', date_born: '1996-09-17' },
    { id: 12, name: 'Oscar Piastri', board_name: 'PIA', number: '81', country: 'Australia', date_born: '2001-04-06' },
    { id: 13, name: 'Pierre Gasly', board_name: 'GAS', number: '10', country: 'France', date_born: '1996-02-07' },
    { id: 14, name: 'Guanyu Zhou', board_name: 'ZHO', number: '24', country: 'China', date_born: '1999-05-30' },
    { id: 15, name: 'Yuki Tsunoda', board_name: 'TSU', number: '22', country: 'Japan', date_born: '2000-05-11' },
    { id: 16, name: 'Kevin Magnussen', board_name: 'MAG', number: '20', country: 'Denmark', date_born: '1992-10-05' },
    { id: 17, name: 'Alexander Albon', board_name: 'ALB', number: '23', country: 'Thailand', date_born: '1996-03-23' },
    { id: 18, name: 'Logan Sargeant', board_name: 'SAR', number: '2', country: 'United States', date_born: '2000-12-31' },
    { id: 19, name: 'Nyck de Vries', board_name: 'VRI', number: '21', country: 'Netherlands', date_born: '1995-03-06' },
    { id: 20, name: 'Max Verstappen', board_name: 'VER', number: '1', country: 'Netherlands', date_born: '1997-09-30' },
    { id: 21, name: 'Daniel Ricciardo', board_name: 'RIC', number: '3', country: 'Australia', date_born: '1989-07-01' },
    { id: 22, name: 'Sebastian Vettel', board_name: 'VET', number: '5', country: 'Germany', date_born: '1987-07-03' },
    { id: 23, name: 'Mick Schumacher', board_name: 'MSC', number: '47', country: 'Germany', date_born: '1999-03-22' },
    { id: 24, name: 'Nicholas Latifi', board_name: 'LAT', number: '6', country: 'Canada', date_born: '1995-06-29' },
    { id: 25, name: 'Liam Lawson', board_name: 'LAW', number: '40', country: 'Australia', date_born: '2002-02-11' },
];

export const circuits: Circuit[] = [
    { id: 1, name: 'Albert Park Circuit', city: 'Melbourne', country: 'Australia', laps: 58, length: 5278, wr_time: '1:20:235' },
    { id: 2, name: 'Autodromo Enzo e Dino Ferrari', city: 'Imola', country: 'Italy', laps: 63, length: 4909, wr_time: '1:15:484' },
    { id: 3, name: 'Autodromo Hermanos Rodriguez', city: 'Mexico City', country: 'Mexico', laps: 71, length: 4304, wr_time: '1:17:774' },
    { id: 4, name: 'Autodromo Jose Carlos Pace Interlagos', city: 'Sao Paulo', country: 'Brazil', laps: 71, length: 4309, wr_time: '1:10:540' },
    { id: 5, name: 'Autodromo Nazionale di Monza', city: 'Monza', country: 'Italy', laps: 53, length: 5793, wr_time: '1:21:046' },
    { id: 6, name: 'Bahrain International Circuit', city: 'Sakhir', country: 'Bahrain', laps: 57, length: 5412, wr_time: '1:31:447' },
    { id: 7, name: 'Baku City Circuit', city: 'Baku', country: 'Azerbaijan', laps: 51, length: 6003, wr_time: '1:43:009' },
    { id: 8, name: 'Circuit de Barcelona-Catalunya', city: 'Montmelo', country: 'Spain', laps: 66, length: 4675, wr_time: '1:16:741' },
    { id: 9, name: 'Circuit de Monaco', city: 'Monte Carlo', country: 'Monaco', laps: 78, length: 3337, wr_time: '1:12:909' },
    { id: 10, name: 'Circuit de Spa - Francorchamps', city: 'Stavelot', country: 'Belgium', laps: 44, length: 7004, wr_time: '1:46:286' },
    { id: 11, name: 'Circuit Gilles-Villeneuve', city: 'Montreal', country: 'Canada', laps: 70, length: 4361, wr_time: '1:13:078' },
    { id: 12, name: 'Circuit of the Americas', city: 'Austin', country: 'United States', laps: 56, length: 5513, wr_time: '1:36:169' },
    { id: 13, name: 'Circuit Zandvoort', city: 'Zandvoort', country: 'Netherlands', laps: 72, length: 4259, wr_time: '1:11:097' },
    { id: 14, name: 'Hungaroring', city: 'Mogyorod', country: 'Hungary', laps: 70, length: 4381, wr_time: '1:16:627' },
    { id: 15, name: 'Jeddah Corniche Circuit', city: 'Jeddah', country: 'Saudi Arabia', laps: 50, length: 6174, wr_time: '1:30:734' },
    { id: 16, name: 'Las Vegas Street Circuit', city: 'Paradise', country: 'United States', laps: 50, length: 6120, wr_time: '1:35:490' },
    { id: 17, name: 'Losail International Circuit', city: 'Doha', country: 'Qatar', laps: 57, length: 5418, wr_time: '1:23:196' },
    { id: 18, name: 'Marina Bay Street Circuit', city: 'Marina Bay', country: 'Singapore', laps: 61, length: 5063, wr_time: '1:36:015' },
    { id: 19, name: 'Miami International Autodrome', city: 'Miami Gardens', country: 'United States', laps: 57, length: 5412, wr_time: '1:31:361' },
    { id: 20, name: 'Red Bull Ring', city: 'Spielberg', country: 'Austria', laps: 71, length: 4318, wr_time: '1:05:619' },
    { id: 21, name: 'Silverstone Circuit', city: 'Silverstone', country: 'United Kingdom', laps: 52, length: 5891, wr_time: '1:27:097' },
    { id: 22, name: 'Suzuka International Racing Course', city: 'Suzuka', country: 'Japan', laps: 53, length: 5807, wr_time: '1:30:983' },
    { id: 23, name: 'Yas Marina Circuit', city: 'Abu Dhabi', country: 'United Arab Emirates', laps: 55, length: 5281, wr_time: '1:26:103' },
    { id: 24, name: 'Sochi Autodrom', city: 'Soci', country: 'Russia', laps: 53, length: 5848, wr_time: '1:35:761' },
    { id: 25, name: 'Autodromo Internazionale del Mugello', city: 'Scarperia e San Piero', country: 'Italy', laps: 59, length: 5245, wr_time: '1:18:833' },
    { id: 26, name: 'Circuit Paul Ricard', city: 'Le Castellet', country: 'France', laps: 53, length: 5842, wr_time: '1:32:740' },
];

export const teams_stands: TeamStand[] = [
    { id: 1, id_season: 2023, id_team: 8, points: 860 },
    { id: 2, id_season: 2023, id_team: 4, points: 409 },
    { id: 3, id_season: 2023, id_team: 1, points: 406 },
    { id: 4, id_season: 2023, id_team: 6, points: 302 },
    { id: 5, id_season: 2023, id_team: 5, points: 280 },
    { id: 6, id_season: 2023, id_team: 10, points: 120 },
    { id: 7, id_season: 2023, id_team: 7, points: 28 },
    { id: 8, id_season: 2023, id_team: 9, points: 25 },
    { id: 9, id_season: 2023, id_team: 2, points: 16 },
    { id: 10, id_season: 2023, id_team: 3, points: 12 },
    { id: 11, id_season: 2022, id_team: 8, points: 759 },
    { id: 12, id_season: 2022, id_team: 1, points: 554 },
    { id: 13, id_season: 2022, id_team: 4, points: 515 },
    { id: 14, id_season: 2022, id_team: 10, points: 173 },
    { id: 15, id_season: 2022, id_team: 6, points: 159 },
    { id: 16, id_season: 2022, id_team: 2, points: 55 },
    { id: 17, id_season: 2022, id_team: 5, points: 55 },
    { id: 18, id_season: 2022, id_team: 3, points: 37 },
    { id: 19, id_season: 2022, id_team: 9, points: 35 },
    { id: 20, id_season: 2022, id_team: 7, points: 8 },
];

export const drivers_stands: DriverStand[] = [
    { id: 1, id_season: 2023, id_driver: 20, id_driver_team: 8, points: 575 },
    { id: 2, id_season: 2023, id_driver: 2, id_driver_team: 8, points: 285 },
    { id: 3, id_season: 2023, id_driver: 4, id_driver_team: 4, points: 234 },
    { id: 4, id_season: 2023, id_driver: 3, id_driver_team: 5, points: 206 },
    { id: 5, id_season: 2023, id_driver: 9, id_driver_team: 1, points: 206 },
    { id: 6, id_season: 2023, id_driver: 1, id_driver_team: 6, points: 205 },
    { id: 7, id_season: 2023, id_driver: 5, id_driver_team: 1, points: 200 },
    { id: 8, id_season: 2023, id_driver: 7, id_driver_team: 4, points: 175 },
    { id: 9, id_season: 2023, id_driver: 12, id_driver_team: 6, points: 97 },
    { id: 10, id_season: 2023, id_driver: 6, id_driver_team: 5, points: 74 },
    { id: 11, id_season: 2023, id_driver: 13, id_driver_team: 10, points: 62 },
    { id: 12, id_season: 2023, id_driver: 11, id_driver_team: 10, points: 58 },
    { id: 13, id_season: 2023, id_driver: 17, id_driver_team: 7, points: 27 },
    { id: 14, id_season: 2023, id_driver: 15, id_driver_team: 9, points: 17 },
    { id: 15, id_season: 2023, id_driver: 10, id_driver_team: 2, points: 10 },
    { id: 16, id_season: 2023, id_driver: 8, id_driver_team: 3, points: 9 },
    { id: 17, id_season: 2023, id_driver: 21, id_driver_team: 9, points: 6 },
    { id: 18, id_season: 2023, id_driver: 14, id_driver_team: 2, points: 6 },
    { id: 19, id_season: 2023, id_driver: 16, id_driver_team: 3, points: 3 },
    { id: 20, id_season: 2023, id_driver: 25, id_driver_team: 9, points: 2 },
    { id: 21, id_season: 2023, id_driver: 18, id_driver_team: 7, points: 1 },
    { id: 22, id_season: 2023, id_driver: 19, id_driver_team: 9, points: 0 },
    { id: 23, id_season: 2022, id_driver: 20, id_driver_team: 8, points: 454 },
    { id: 24, id_season: 2022, id_driver: 9, id_driver_team: 1, points: 308 },
    { id: 25, id_season: 2022, id_driver: 2, id_driver_team: 8, points: 305 },
    { id: 26, id_season: 2022, id_driver: 7, id_driver_team: 4, points: 275 },
    { id: 27, id_season: 2022, id_driver: 5, id_driver_team: 1, points: 246 },
    { id: 28, id_season: 2022, id_driver: 4, id_driver_team: 4, points: 240 },
    { id: 29, id_season: 2022, id_driver: 1, id_driver_team: 6, points: 122 },
    { id: 30, id_season: 2022, id_driver: 11, id_driver_team: 10, points: 92 },
    { id: 31, id_season: 2022, id_driver: 3, id_driver_team: 10, points: 81 },
    { id: 32, id_season: 2022, id_driver: 10, id_driver_team: 2, points: 49 },
    { id: 33, id_season: 2022, id_driver: 21, id_driver_team: 6, points: 37 },
    { id: 34, id_season: 2022, id_driver: 22, id_driver_team: 5, points: 37 },
    { id: 35, id_season: 2022, id_driver: 16, id_driver_team: 3, points: 25 },
    { id: 36, id_season: 2022, id_driver: 13, id_driver_team: 9, points: 23 },
    { id: 37, id_season: 2022, id_driver: 6, id_driver_team: 5, points: 18 },
    { id: 38, id_season: 2022, id_driver: 23, id_driver_team: 3, points: 12 },
    { id: 39, id_season: 2022, id_driver: 15, id_driver_team: 9, points: 12 },
    { id: 40, id_season: 2022, id_driver: 14, id_driver_team: 2, points: 6 },
    { id: 41, id_season: 2022, id_driver: 17, id_driver_team: 7, points: 4 },
    { id: 42, id_season: 2022, id_driver: 24, id_driver_team: 7, points: 2 },
    { id: 43, id_season: 2022, id_driver: 19, id_driver_team: 7, points: 2 },
    { id: 44, id_season: 2022, id_driver: 8, id_driver_team: 5, points: 0 },
];

export const races: Race[] = [
    { id: 1, id_season: 2023, id_circuit: 6, date_race: '2023-03-05', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 14 },
    { id: 2, id_season: 2023, id_circuit: 15, date_race: '2023-03-19', id_driver_win: 2, id_driver_pole: 2, id_driver_fastlap: 20 },
    { id: 3, id_season: 2023, id_circuit: 1, date_race: '2023-04-02', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 2 },
    { id: 4, id_season: 2023, id_circuit: 7, date_race: '2023-04-30', id_driver_win: 2, id_driver_pole: 9, id_driver_fastlap: 7 },
    { id: 5, id_season: 2023, id_circuit: 19, date_race: '2023-05-07', id_driver_win: 20, id_driver_pole: 2, id_driver_fastlap: 20 },
    { id: 6, id_season: 2023, id_circuit: 2, date_race: '2023-05-21', id_driver_win: null, id_driver_pole: null, id_driver_fastlap: null },
    { id: 7, id_season: 2023, id_circuit: 9, date_race: '2023-05-28', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 4 },
    { id: 8, id_season: 2023, id_circuit: 8, date_race: '2023-06-04', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 9, id_season: 2023, id_circuit: 11, date_race: '2023-06-18', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 2 },
    { id: 10, id_season: 2023, id_circuit: 20, date_race: '2023-07-02', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 11, id_season: 2023, id_circuit: 21, date_race: '2023-07-09', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 12, id_season: 2023, id_circuit: 14, date_race: '2023-07-23', id_driver_win: 20, id_driver_pole: 4, id_driver_fastlap: 20 },
    { id: 13, id_season: 2023, id_circuit: 10, date_race: '2023-07-30', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 4 },
    { id: 14, id_season: 2023, id_circuit: 13, date_race: '2023-08-27', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 3 },
    { id: 15, id_season: 2023, id_circuit: 5, date_race: '2023-09-03', id_driver_win: 20, id_driver_pole: 5, id_driver_fastlap: 12 },
    { id: 16, id_season: 2023, id_circuit: 18, date_race: '2023-09-17', id_driver_win: 5, id_driver_pole: 5, id_driver_fastlap: 4 },
    { id: 17, id_season: 2023, id_circuit: 22, date_race: '2023-09-24', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 18, id_season: 2023, id_circuit: 17, date_race: '2023-10-08', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 19, id_season: 2023, id_circuit: 12, date_race: '2023-10-22', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 15 },
    { id: 20, id_season: 2023, id_circuit: 3, date_race: '2023-10-29', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 4 },
    { id: 21, id_season: 2023, id_circuit: 4, date_race: '2023-11-05', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 1 },
    { id: 22, id_season: 2023, id_circuit: 16, date_race: '2023-11-18', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 12 },
    { id: 23, id_season: 2023, id_circuit: 23, date_race: '2023-11-26', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 24, id_season: 2022, id_circuit: 6, date_race: '2022-03-20', id_driver_win: 9, id_driver_pole: 9, id_driver_fastlap: 9 },
    { id: 25, id_season: 2022, id_circuit: 15, date_race: '2022-03-27', id_driver_win: 20, id_driver_pole: 2, id_driver_fastlap: 9 },
    { id: 26, id_season: 2022, id_circuit: 1, date_race: '2022-04-10', id_driver_win: 9, id_driver_pole: 9, id_driver_fastlap: 9 },
    { id: 27, id_season: 2022, id_circuit: 2, date_race: '2022-04-24', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 28, id_season: 2022, id_circuit: 19, date_race: '2022-05-08', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 20 },
    { id: 29, id_season: 2022, id_circuit: 8, date_race: '2022-05-22', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 2 },
    { id: 30, id_season: 2022, id_circuit: 9, date_race: '2022-05-29', id_driver_win: 2, id_driver_pole: 9, id_driver_fastlap: 1 },
    { id: 31, id_season: 2022, id_circuit: 7, date_race: '2022-06-12', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 2 },
    { id: 32, id_season: 2022, id_circuit: 11, date_race: '2022-06-19', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 5 },
    { id: 33, id_season: 2022, id_circuit: 21, date_race: '2022-07-03', id_driver_win: 5, id_driver_pole: 5, id_driver_fastlap: 4 },
    { id: 34, id_season: 2022, id_circuit: 20, date_race: '2022-07-10', id_driver_win: 9, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 35, id_season: 2022, id_circuit: 26, date_race: '2022-07-24', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 5 },
    { id: 36, id_season: 2022, id_circuit: 14, date_race: '2022-07-31', id_driver_win: 20, id_driver_pole: 7, id_driver_fastlap: 4 },
    { id: 37, id_season: 2022, id_circuit: 10, date_race: '2022-08-28', id_driver_win: 20, id_driver_pole: 5, id_driver_fastlap: 20 },
    { id: 38, id_season: 2022, id_circuit: 13, date_race: '2022-09-04', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 20 },
    { id: 39, id_season: 2022, id_circuit: 5, date_race: '2022-09-11', id_driver_win: 20, id_driver_pole: 9, id_driver_fastlap: 2 },
    { id: 40, id_season: 2022, id_circuit: 18, date_race: '2022-10-02', id_driver_win: 2, id_driver_pole: 9, id_driver_fastlap: 7 },
    { id: 41, id_season: 2022, id_circuit: 22, date_race: '2022-10-09', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 14 },
    { id: 42, id_season: 2022, id_circuit: 12, date_race: '2022-10-23', id_driver_win: 20, id_driver_pole: 5, id_driver_fastlap: 7 },
    { id: 43, id_season: 2022, id_circuit: 3, date_race: '2022-10-30', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 7 },
    { id: 44, id_season: 2022, id_circuit: 4, date_race: '2022-11-13', id_driver_win: 7, id_driver_pole: 16, id_driver_fastlap: 7 },
    { id: 45, id_season: 2022, id_circuit: 23, date_race: '2022-11-20', id_driver_win: 20, id_driver_pole: 20, id_driver_fastlap: 1 },
];

export const race_details: RaceDetail[] = [
    { id_race: 1, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 1, id_driver: 2, id_driver_team: 8, start_pos: '2', end_pos: '2' },
    { id_race: 1, id_driver: 3, id_driver_team: 5, start_pos: '5', end_pos: '3' },
    { id_race: 1, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '4' },
    { id_race: 1, id_driver: 4, id_driver_team: 4, start_pos: '7', end_pos: '5' },
    { id_race: 1, id_driver: 6, id_driver_team: 5, start_pos: '8', end_pos: '6' },
    { id_race: 1, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '7' },
    { id_race: 1, id_driver: 10, id_driver_team: 2, start_pos: '12', end_pos: '8' },
    { id_race: 1, id_driver: 13, id_driver_team: 10, start_pos: '21', end_pos: '9' },
    { id_race: 1, id_driver: 17, id_driver_team: 7, start_pos: '15', end_pos: '10' },
    { id_race: 1, id_driver: 15, id_driver_team: 9, start_pos: '14', end_pos: '11' },
    { id_race: 1, id_driver: 18, id_driver_team: 7, start_pos: '16', end_pos: '12' },
    { id_race: 1, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '13' },
    { id_race: 1, id_driver: 19, id_driver_team: 9, start_pos: '19', end_pos: '14' },
    { id_race: 1, id_driver: 8, id_driver_team: 3, start_pos: '10', end_pos: '15' },
    { id_race: 1, id_driver: 14, id_driver_team: 2, start_pos: '13', end_pos: '16' },
    { id_race: 1, id_driver: 1, id_driver_team: 6, start_pos: '11', end_pos: '17' },
    { id_race: 1, id_driver: 11, id_driver_team: 10, start_pos: '9', end_pos: 'OUT' },
    { id_race: 1, id_driver: 9, id_driver_team: 1, start_pos: '3', end_pos: 'OUT' },
    { id_race: 1, id_driver: 12, id_driver_team: 6, start_pos: '18', end_pos: 'OUT' },
    { id_race: 2, id_driver: 2, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 2, id_driver: 20, id_driver_team: 8, start_pos: '15', end_pos: '2' },
    { id_race: 2, id_driver: 3, id_driver_team: 5, start_pos: '2', end_pos: '3' },
    { id_race: 2, id_driver: 7, id_driver_team: 4, start_pos: '3', end_pos: '4' },
    { id_race: 2, id_driver: 4, id_driver_team: 4, start_pos: '7', end_pos: '5' },
    { id_race: 2, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '6' },
    { id_race: 2, id_driver: 9, id_driver_team: 1, start_pos: '12', end_pos: '7' },
    { id_race: 2, id_driver: 11, id_driver_team: 10, start_pos: '6', end_pos: '8' },
    { id_race: 2, id_driver: 13, id_driver_team: 10, start_pos: '9', end_pos: '9' },
    { id_race: 2, id_driver: 16, id_driver_team: 3, start_pos: '13', end_pos: '10' },
    { id_race: 2, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '11' },
    { id_race: 2, id_driver: 8, id_driver_team: 3, start_pos: '10', end_pos: '12' },
    { id_race: 2, id_driver: 14, id_driver_team: 2, start_pos: '11', end_pos: '13' },
    { id_race: 2, id_driver: 19, id_driver_team: 9, start_pos: '18', end_pos: '14' },
    { id_race: 2, id_driver: 12, id_driver_team: 6, start_pos: '8', end_pos: '15' },
    { id_race: 2, id_driver: 18, id_driver_team: 7, start_pos: '20', end_pos: '16' },
    { id_race: 2, id_driver: 1, id_driver_team: 6, start_pos: '19', end_pos: '17' },
    { id_race: 2, id_driver: 10, id_driver_team: 2, start_pos: '14', end_pos: '18' },
    { id_race: 2, id_driver: 17, id_driver_team: 7, start_pos: '17', end_pos: 'OUT' },
    { id_race: 2, id_driver: 6, id_driver_team: 5, start_pos: '5', end_pos: 'OUT' },
    { id_race: 3, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 3, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '2' },
    { id_race: 3, id_driver: 3, id_driver_team: 5, start_pos: '4', end_pos: '3' },
    { id_race: 3, id_driver: 6, id_driver_team: 5, start_pos: '6', end_pos: '4' },
    { id_race: 3, id_driver: 2, id_driver_team: 8, start_pos: 'PL', end_pos: '5' },
    { id_race: 3, id_driver: 1, id_driver_team: 6, start_pos: '13', end_pos: '6' },
    { id_race: 3, id_driver: 8, id_driver_team: 3, start_pos: '10', end_pos: '7' },
    { id_race: 3, id_driver: 12, id_driver_team: 6, start_pos: '16', end_pos: '8' },
    { id_race: 3, id_driver: 14, id_driver_team: 2, start_pos: '17', end_pos: '9' },
    { id_race: 3, id_driver: 15, id_driver_team: 9, start_pos: '12', end_pos: '10' },
    { id_race: 3, id_driver: 10, id_driver_team: 2, start_pos: 'PL', end_pos: '11' },
    { id_race: 3, id_driver: 5, id_driver_team: 1, start_pos: '5', end_pos: '12' },
    { id_race: 3, id_driver: 13, id_driver_team: 10, start_pos: '9', end_pos: '13' },
    { id_race: 3, id_driver: 11, id_driver_team: 10, start_pos: '11', end_pos: '14' },
    { id_race: 3, id_driver: 19, id_driver_team: 9, start_pos: '15', end_pos: '15' },
    { id_race: 3, id_driver: 18, id_driver_team: 7, start_pos: '18', end_pos: '16' },
    { id_race: 3, id_driver: 16, id_driver_team: 3, start_pos: '14', end_pos: '17' },
    { id_race: 3, id_driver: 7, id_driver_team: 4, start_pos: '2', end_pos: 'OUT' },
    { id_race: 3, id_driver: 17, id_driver_team: 7, start_pos: '8', end_pos: 'OUT' },
    { id_race: 3, id_driver: 9, id_driver_team: 1, start_pos: '7', end_pos: 'OUT' },
    { id_race: 24, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '1' },
    { id_race: 24, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '2' },
    { id_race: 24, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '3' },
    { id_race: 24, id_driver: 7, id_driver_team: 4, start_pos: '9', end_pos: '4' },
    { id_race: 24, id_driver: 16, id_driver_team: 3, start_pos: '7', end_pos: '5' },
    { id_race: 24, id_driver: 10, id_driver_team: 2, start_pos: '6', end_pos: '6' },
    { id_race: 24, id_driver: 11, id_driver_team: 10, start_pos: '11', end_pos: '7' },
    { id_race: 24, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '8' },
    { id_race: 24, id_driver: 3, id_driver_team: 10, start_pos: '8', end_pos: '9' },
    { id_race: 24, id_driver: 14, id_driver_team: 2, start_pos: '15', end_pos: '10' },
    { id_race: 24, id_driver: 23, id_driver_team: 3, start_pos: '12', end_pos: '11' },
    { id_race: 24, id_driver: 6, id_driver_team: 5, start_pos: '19', end_pos: '12' },
    { id_race: 24, id_driver: 17, id_driver_team: 7, start_pos: '14', end_pos: '13' },
    { id_race: 24, id_driver: 21, id_driver_team: 6, start_pos: '18', end_pos: '14' },
    { id_race: 24, id_driver: 1, id_driver_team: 6, start_pos: '13', end_pos: '15' },
    { id_race: 24, id_driver: 24, id_driver_team: 7, start_pos: '20', end_pos: '16' },
    { id_race: 24, id_driver: 8, id_driver_team: 5, start_pos: '17', end_pos: '17' },
    { id_race: 24, id_driver: 2, id_driver_team: 8, start_pos: '4', end_pos: '18' },
    { id_race: 24, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '19' },
    { id_race: 24, id_driver: 13, id_driver_team: 9, start_pos: '10', end_pos: 'OUT' },
    { id_race: 25, id_driver: 20, id_driver_team: 8, start_pos: '4', end_pos: '1' },
    { id_race: 25, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '2' },
    { id_race: 25, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '3' },
    { id_race: 25, id_driver: 2, id_driver_team: 8, start_pos: '1', end_pos: '4' },
    { id_race: 25, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '5' },
    { id_race: 25, id_driver: 11, id_driver_team: 10, start_pos: '5', end_pos: '6' },
    { id_race: 25, id_driver: 1, id_driver_team: 6, start_pos: '11', end_pos: '7' },
    { id_race: 25, id_driver: 13, id_driver_team: 9, start_pos: '9', end_pos: '8' },
    { id_race: 25, id_driver: 16, id_driver_team: 3, start_pos: '10', end_pos: '9' },
    { id_race: 25, id_driver: 4, id_driver_team: 4, start_pos: '15', end_pos: '10' },
    { id_race: 25, id_driver: 14, id_driver_team: 2, start_pos: '12', end_pos: '11' },
    { id_race: 25, id_driver: 8, id_driver_team: 5, start_pos: '17', end_pos: '12' },
    { id_race: 25, id_driver: 6, id_driver_team: 5, start_pos: '13', end_pos: '13' },
    { id_race: 25, id_driver: 17, id_driver_team: 7, start_pos: '16', end_pos: '14' },
    { id_race: 25, id_driver: 10, id_driver_team: 2, start_pos: '8', end_pos: 'OUT' },
    { id_race: 25, id_driver: 3, id_driver_team: 10, start_pos: '7', end_pos: 'OUT' },
    { id_race: 25, id_driver: 21, id_driver_team: 6, start_pos: '14', end_pos: 'OUT' },
    { id_race: 25, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: 'OUT' },
    { id_race: 25, id_driver: 23, id_driver_team: 3, start_pos: '', end_pos: '' },
    { id_race: 25, id_driver: 15, id_driver_team: 9, start_pos: '19', end_pos: 'OUT' },
    { id_race: 26, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '1' },
    { id_race: 26, id_driver: 2, id_driver_team: 8, start_pos: '3', end_pos: '2' },
    { id_race: 26, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '3' },
    { id_race: 26, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '4' },
    { id_race: 26, id_driver: 1, id_driver_team: 6, start_pos: '4', end_pos: '5' },
    { id_race: 26, id_driver: 21, id_driver_team: 6, start_pos: '7', end_pos: '6' },
    { id_race: 26, id_driver: 11, id_driver_team: 10, start_pos: '8', end_pos: '7' },
    { id_race: 26, id_driver: 10, id_driver_team: 2, start_pos: '12', end_pos: '8' },
    { id_race: 26, id_driver: 13, id_driver_team: 9, start_pos: '11', end_pos: '9' },
    { id_race: 26, id_driver: 17, id_driver_team: 7, start_pos: '20', end_pos: '10' },
    { id_race: 26, id_driver: 14, id_driver_team: 2, start_pos: '14', end_pos: '11' },
    { id_race: 26, id_driver: 6, id_driver_team: 5, start_pos: '19', end_pos: '12' },
    { id_race: 26, id_driver: 23, id_driver_team: 3, start_pos: '15', end_pos: '13' },
    { id_race: 26, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: '14' },
    { id_race: 26, id_driver: 15, id_driver_team: 9, start_pos: '13', end_pos: '15' },
    { id_race: 26, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: '16' },
    { id_race: 26, id_driver: 3, id_driver_team: 10, start_pos: '10', end_pos: '17' },
    { id_race: 26, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: 'OUT' },
    { id_race: 26, id_driver: 22, id_driver_team: 5, start_pos: '17', end_pos: 'OUT' },
    { id_race: 26, id_driver: 5, id_driver_team: 1, start_pos: '9', end_pos: 'OUT' },
    { id_race: 27, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 27, id_driver: 2, id_driver_team: 8, start_pos: '3', end_pos: '2' },
    { id_race: 27, id_driver: 1, id_driver_team: 6, start_pos: '5', end_pos: '3' },
    { id_race: 27, id_driver: 7, id_driver_team: 4, start_pos: '11', end_pos: '4' },
    { id_race: 27, id_driver: 10, id_driver_team: 2, start_pos: '7', end_pos: '5' },
    { id_race: 27, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '6' },
    { id_race: 27, id_driver: 15, id_driver_team: 9, start_pos: '12', end_pos: '7' },
    { id_race: 27, id_driver: 22, id_driver_team: 5, start_pos: '13', end_pos: '8' },
    { id_race: 27, id_driver: 16, id_driver_team: 3, start_pos: '8', end_pos: '9' },
    { id_race: 27, id_driver: 6, id_driver_team: 5, start_pos: '15', end_pos: '10' },
    { id_race: 27, id_driver: 17, id_driver_team: 7, start_pos: '18', end_pos: '11' },
    { id_race: 27, id_driver: 13, id_driver_team: 9, start_pos: '17', end_pos: '12' },
    { id_race: 27, id_driver: 4, id_driver_team: 4, start_pos: '14', end_pos: '13' },
    { id_race: 27, id_driver: 11, id_driver_team: 10, start_pos: '16', end_pos: '14' },
    { id_race: 27, id_driver: 14, id_driver_team: 2, start_pos: 'PL', end_pos: '15' },
    { id_race: 27, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: '16' },
    { id_race: 27, id_driver: 23, id_driver_team: 3, start_pos: '10', end_pos: '17' },
    { id_race: 27, id_driver: 21, id_driver_team: 6, start_pos: '6', end_pos: '18' },
    { id_race: 27, id_driver: 3, id_driver_team: 10, start_pos: '9', end_pos: 'OUT' },
    { id_race: 27, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: 'OUT' },
    { id_race: 28, id_driver: 20, id_driver_team: 8, start_pos: '3', end_pos: '1' },
    { id_race: 28, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '2' },
    { id_race: 28, id_driver: 5, id_driver_team: 1, start_pos: '2', end_pos: '3' },
    { id_race: 28, id_driver: 2, id_driver_team: 8, start_pos: '4', end_pos: '4' },
    { id_race: 28, id_driver: 7, id_driver_team: 4, start_pos: '12', end_pos: '5' },
    { id_race: 28, id_driver: 4, id_driver_team: 4, start_pos: '6', end_pos: '6' },
    { id_race: 28, id_driver: 10, id_driver_team: 2, start_pos: '5', end_pos: '7' },
    { id_race: 28, id_driver: 11, id_driver_team: 10, start_pos: '20', end_pos: '8' },
    { id_race: 28, id_driver: 17, id_driver_team: 7, start_pos: '18', end_pos: '9' },
    { id_race: 28, id_driver: 6, id_driver_team: 5, start_pos: 'PL', end_pos: '10' },
    { id_race: 28, id_driver: 3, id_driver_team: 10, start_pos: '11', end_pos: '11' },
    { id_race: 28, id_driver: 15, id_driver_team: 9, start_pos: '9', end_pos: '12' },
    { id_race: 28, id_driver: 21, id_driver_team: 6, start_pos: '14', end_pos: '13' },
    { id_race: 28, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: '14' },
    { id_race: 28, id_driver: 23, id_driver_team: 3, start_pos: '15', end_pos: '15' },
    { id_race: 28, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: '16' },
    { id_race: 28, id_driver: 22, id_driver_team: 5, start_pos: 'PL', end_pos: '17' },
    { id_race: 28, id_driver: 13, id_driver_team: 9, start_pos: '7', end_pos: '18' },
    { id_race: 28, id_driver: 1, id_driver_team: 6, start_pos: '8', end_pos: '19' },
    { id_race: 28, id_driver: 14, id_driver_team: 2, start_pos: '17', end_pos: '20' },
    { id_race: 29, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 29, id_driver: 2, id_driver_team: 8, start_pos: '5', end_pos: '2' },
    { id_race: 29, id_driver: 7, id_driver_team: 4, start_pos: '4', end_pos: '3' },
    { id_race: 29, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '4' },
    { id_race: 29, id_driver: 4, id_driver_team: 4, start_pos: '6', end_pos: '5' },
    { id_race: 29, id_driver: 10, id_driver_team: 2, start_pos: '7', end_pos: '6' },
    { id_race: 29, id_driver: 11, id_driver_team: 10, start_pos: '12', end_pos: '7' },
    { id_race: 29, id_driver: 1, id_driver_team: 6, start_pos: '11', end_pos: '8' },
    { id_race: 29, id_driver: 3, id_driver_team: 10, start_pos: '20', end_pos: '9' },
    { id_race: 29, id_driver: 15, id_driver_team: 9, start_pos: '13', end_pos: '10' },
    { id_race: 29, id_driver: 22, id_driver_team: 5, start_pos: '16', end_pos: '11' },
    { id_race: 29, id_driver: 21, id_driver_team: 6, start_pos: '9', end_pos: '12' },
    { id_race: 29, id_driver: 13, id_driver_team: 9, start_pos: '14', end_pos: '13' },
    { id_race: 29, id_driver: 23, id_driver_team: 3, start_pos: '10', end_pos: '14' },
    { id_race: 29, id_driver: 6, id_driver_team: 5, start_pos: '17', end_pos: '15' },
    { id_race: 29, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: '16' },
    { id_race: 29, id_driver: 16, id_driver_team: 3, start_pos: '8', end_pos: '17' },
    { id_race: 29, id_driver: 17, id_driver_team: 7, start_pos: '18', end_pos: '18' },
    { id_race: 29, id_driver: 14, id_driver_team: 2, start_pos: '15', end_pos: 'OUT' },
    { id_race: 29, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: 'OUT' },
    { id_race: 30, id_driver: 2, id_driver_team: 8, start_pos: '3', end_pos: '1' },
    { id_race: 30, id_driver: 5, id_driver_team: 1, start_pos: '2', end_pos: '2' },
    { id_race: 30, id_driver: 20, id_driver_team: 8, start_pos: '4', end_pos: '3' },
    { id_race: 30, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '4' },
    { id_race: 30, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '5' },
    { id_race: 30, id_driver: 1, id_driver_team: 6, start_pos: '5', end_pos: '6' },
    { id_race: 30, id_driver: 3, id_driver_team: 10, start_pos: '7', end_pos: '7' },
    { id_race: 30, id_driver: 4, id_driver_team: 4, start_pos: '8', end_pos: '8' },
    { id_race: 30, id_driver: 10, id_driver_team: 2, start_pos: '12', end_pos: '9' },
    { id_race: 30, id_driver: 22, id_driver_team: 5, start_pos: '9', end_pos: '10' },
    { id_race: 30, id_driver: 13, id_driver_team: 9, start_pos: '17', end_pos: '11' },
    { id_race: 30, id_driver: 11, id_driver_team: 10, start_pos: '10', end_pos: '12' },
    { id_race: 30, id_driver: 21, id_driver_team: 6, start_pos: '14', end_pos: '13' },
    { id_race: 30, id_driver: 6, id_driver_team: 5, start_pos: '18', end_pos: '14' },
    { id_race: 30, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: '15' },
    { id_race: 30, id_driver: 14, id_driver_team: 2, start_pos: '20', end_pos: '16' },
    { id_race: 30, id_driver: 15, id_driver_team: 9, start_pos: '11', end_pos: '17' },
    { id_race: 30, id_driver: 17, id_driver_team: 7, start_pos: '16', end_pos: '18' },
    { id_race: 30, id_driver: 23, id_driver_team: 3, start_pos: '15', end_pos: '19' },
    { id_race: 30, id_driver: 16, id_driver_team: 3, start_pos: '13', end_pos: '20' },
    { id_race: 31, id_driver: 20, id_driver_team: 8, start_pos: '3', end_pos: '1' },
    { id_race: 31, id_driver: 2, id_driver_team: 8, start_pos: '2', end_pos: '2' },
    { id_race: 31, id_driver: 7, id_driver_team: 4, start_pos: '5', end_pos: '3' },
    { id_race: 31, id_driver: 4, id_driver_team: 4, start_pos: '7', end_pos: '4' },
    { id_race: 31, id_driver: 13, id_driver_team: 9, start_pos: '6', end_pos: '5' },
    { id_race: 31, id_driver: 22, id_driver_team: 5, start_pos: '9', end_pos: '6' },
    { id_race: 31, id_driver: 3, id_driver_team: 10, start_pos: '10', end_pos: '7' },
    { id_race: 31, id_driver: 21, id_driver_team: 6, start_pos: '12', end_pos: '8' },
    { id_race: 31, id_driver: 1, id_driver_team: 6, start_pos: '11', end_pos: '9' },
    { id_race: 31, id_driver: 11, id_driver_team: 10, start_pos: '13', end_pos: '10' },
    { id_race: 31, id_driver: 10, id_driver_team: 2, start_pos: '15', end_pos: '11' },
    { id_race: 31, id_driver: 17, id_driver_team: 7, start_pos: '17', end_pos: '12' },
    { id_race: 31, id_driver: 15, id_driver_team: 9, start_pos: '8', end_pos: '13' },
    { id_race: 31, id_driver: 23, id_driver_team: 3, start_pos: '20', end_pos: '14' },
    { id_race: 31, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: '15' },
    { id_race: 31, id_driver: 6, id_driver_team: 5, start_pos: '19', end_pos: '16' },
    { id_race: 31, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: 'OUT' },
    { id_race: 31, id_driver: 14, id_driver_team: 2, start_pos: '14', end_pos: 'OUT' },
    { id_race: 31, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: 'OUT' },
    { id_race: 31, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: 'OUT' },
    { id_race: 32, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 32, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '2' },
    { id_race: 32, id_driver: 4, id_driver_team: 4, start_pos: '4', end_pos: '3' },
    { id_race: 32, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: '4' },
    { id_race: 32, id_driver: 9, id_driver_team: 1, start_pos: '19', end_pos: '5' },
    { id_race: 32, id_driver: 11, id_driver_team: 10, start_pos: '7', end_pos: '6' },
    { id_race: 32, id_driver: 10, id_driver_team: 2, start_pos: '11', end_pos: '7' },
    { id_race: 32, id_driver: 14, id_driver_team: 2, start_pos: '10', end_pos: '8' },
    { id_race: 32, id_driver: 3, id_driver_team: 10, start_pos: '2', end_pos: '9' },
    { id_race: 32, id_driver: 6, id_driver_team: 5, start_pos: '17', end_pos: '10' },
    { id_race: 32, id_driver: 21, id_driver_team: 6, start_pos: '9', end_pos: '11' },
    { id_race: 32, id_driver: 22, id_driver_team: 5, start_pos: '16', end_pos: '12' },
    { id_race: 32, id_driver: 17, id_driver_team: 7, start_pos: '12', end_pos: '13' },
    { id_race: 32, id_driver: 13, id_driver_team: 9, start_pos: '15', end_pos: '14' },
    { id_race: 32, id_driver: 1, id_driver_team: 6, start_pos: '14', end_pos: '15' },
    { id_race: 32, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: '16' },
    { id_race: 32, id_driver: 16, id_driver_team: 3, start_pos: '5', end_pos: '17' },
    { id_race: 32, id_driver: 15, id_driver_team: 9, start_pos: '20', end_pos: '18' },
    { id_race: 32, id_driver: 23, id_driver_team: 3, start_pos: '6', end_pos: '19' },
    { id_race: 32, id_driver: 2, id_driver_team: 8, start_pos: '13', end_pos: '20' },
    { id_race: 33, id_driver: 5, id_driver_team: 1, start_pos: '1', end_pos: '1' },
    { id_race: 33, id_driver: 2, id_driver_team: 8, start_pos: '4', end_pos: '2' },
    { id_race: 33, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '3' },
    { id_race: 33, id_driver: 9, id_driver_team: 1, start_pos: '3', end_pos: '4' },
    { id_race: 33, id_driver: 3, id_driver_team: 10, start_pos: '7', end_pos: '5' },
    { id_race: 33, id_driver: 1, id_driver_team: 6, start_pos: '6', end_pos: '6' },
    { id_race: 33, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '7' },
    { id_race: 33, id_driver: 23, id_driver_team: 3, start_pos: '19', end_pos: '8' },
    { id_race: 33, id_driver: 22, id_driver_team: 5, start_pos: '18', end_pos: '9' },
    { id_race: 33, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '10' },
    { id_race: 33, id_driver: 6, id_driver_team: 5, start_pos: '20', end_pos: '11' },
    { id_race: 33, id_driver: 24, id_driver_team: 7, start_pos: '10', end_pos: '12' },
    { id_race: 33, id_driver: 21, id_driver_team: 6, start_pos: '14', end_pos: '13' },
    { id_race: 33, id_driver: 15, id_driver_team: 9, start_pos: '13', end_pos: '14' },
    { id_race: 33, id_driver: 11, id_driver_team: 10, start_pos: '15', end_pos: 'OUT' },
    { id_race: 33, id_driver: 13, id_driver_team: 9, start_pos: '11', end_pos: 'OUT' },
    { id_race: 33, id_driver: 10, id_driver_team: 2, start_pos: '12', end_pos: 'OUT' },
    { id_race: 33, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: 'OUT' },
    { id_race: 33, id_driver: 14, id_driver_team: 2, start_pos: '9', end_pos: 'OUT' },
    { id_race: 33, id_driver: 17, id_driver_team: 7, start_pos: '16', end_pos: 'OUT' },
    { id_race: 34, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '1' },
    { id_race: 34, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '2' },
    { id_race: 34, id_driver: 4, id_driver_team: 4, start_pos: '8', end_pos: '3' },
    { id_race: 34, id_driver: 7, id_driver_team: 4, start_pos: '4', end_pos: '4' },
    { id_race: 34, id_driver: 11, id_driver_team: 10, start_pos: '6', end_pos: '5' },
    { id_race: 34, id_driver: 23, id_driver_team: 3, start_pos: '9', end_pos: '6' },
    { id_race: 34, id_driver: 1, id_driver_team: 6, start_pos: '10', end_pos: '7' },
    { id_race: 34, id_driver: 16, id_driver_team: 3, start_pos: '7', end_pos: '8' },
    { id_race: 34, id_driver: 21, id_driver_team: 6, start_pos: '11', end_pos: '9' },
    { id_race: 34, id_driver: 3, id_driver_team: 10, start_pos: '19', end_pos: '10' },
    { id_race: 34, id_driver: 10, id_driver_team: 2, start_pos: 'PL', end_pos: '11' },
    { id_race: 34, id_driver: 17, id_driver_team: 7, start_pos: '15', end_pos: '12' },
    { id_race: 34, id_driver: 6, id_driver_team: 5, start_pos: '12', end_pos: '13' },
    { id_race: 34, id_driver: 14, id_driver_team: 2, start_pos: '13', end_pos: '14' },
    { id_race: 34, id_driver: 13, id_driver_team: 9, start_pos: '14', end_pos: '15' },
    { id_race: 34, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '16' },
    { id_race: 34, id_driver: 22, id_driver_team: 5, start_pos: '18', end_pos: '17' },
    { id_race: 34, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: 'OUT' },
    { id_race: 34, id_driver: 24, id_driver_team: 7, start_pos: '17', end_pos: 'OUT' },
    { id_race: 34, id_driver: 2, id_driver_team: 8, start_pos: '5', end_pos: 'OUT' },
    { id_race: 35, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 35, id_driver: 4, id_driver_team: 4, start_pos: '4', end_pos: '2' },
    { id_race: 35, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '3' },
    { id_race: 35, id_driver: 2, id_driver_team: 8, start_pos: '3', end_pos: '4' },
    { id_race: 35, id_driver: 5, id_driver_team: 1, start_pos: '19', end_pos: '5' },
    { id_race: 35, id_driver: 3, id_driver_team: 10, start_pos: '7', end_pos: '6' },
    { id_race: 35, id_driver: 1, id_driver_team: 6, start_pos: '5', end_pos: '7' },
    { id_race: 35, id_driver: 11, id_driver_team: 10, start_pos: '10', end_pos: '8' },
    { id_race: 35, id_driver: 21, id_driver_team: 6, start_pos: '9', end_pos: '9' },
    { id_race: 35, id_driver: 6, id_driver_team: 5, start_pos: '15', end_pos: '10' },
    { id_race: 35, id_driver: 22, id_driver_team: 5, start_pos: '12', end_pos: '11' },
    { id_race: 35, id_driver: 13, id_driver_team: 9, start_pos: '14', end_pos: '12' },
    { id_race: 35, id_driver: 17, id_driver_team: 7, start_pos: '13', end_pos: '13' },
    { id_race: 35, id_driver: 10, id_driver_team: 2, start_pos: '11', end_pos: '14' },
    { id_race: 35, id_driver: 23, id_driver_team: 3, start_pos: '17', end_pos: '15' },
    { id_race: 35, id_driver: 14, id_driver_team: 2, start_pos: '16', end_pos: '16' },
    { id_race: 35, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: 'OUT' },
    { id_race: 35, id_driver: 16, id_driver_team: 3, start_pos: '20', end_pos: 'OUT' },
    { id_race: 35, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: 'OUT' },
    { id_race: 35, id_driver: 15, id_driver_team: 9, start_pos: '8', end_pos: 'OUT' },
    { id_race: 36, id_driver: 20, id_driver_team: 8, start_pos: '10', end_pos: '1' },
    { id_race: 36, id_driver: 4, id_driver_team: 4, start_pos: '7', end_pos: '2' },
    { id_race: 36, id_driver: 7, id_driver_team: 4, start_pos: '1', end_pos: '3' },
    { id_race: 36, id_driver: 5, id_driver_team: 1, start_pos: '2', end_pos: '4' },
    { id_race: 36, id_driver: 2, id_driver_team: 8, start_pos: '11', end_pos: '5' },
    { id_race: 36, id_driver: 9, id_driver_team: 1, start_pos: '3', end_pos: '6' },
    { id_race: 36, id_driver: 1, id_driver_team: 6, start_pos: '4', end_pos: '7' },
    { id_race: 36, id_driver: 3, id_driver_team: 10, start_pos: '6', end_pos: '8' },
    { id_race: 36, id_driver: 11, id_driver_team: 10, start_pos: '5', end_pos: '9' },
    { id_race: 36, id_driver: 22, id_driver_team: 5, start_pos: '18', end_pos: '10' },
    { id_race: 36, id_driver: 6, id_driver_team: 5, start_pos: '14', end_pos: '11' },
    { id_race: 36, id_driver: 13, id_driver_team: 9, start_pos: 'PL', end_pos: '12' },
    { id_race: 36, id_driver: 14, id_driver_team: 2, start_pos: '12', end_pos: '13' },
    { id_race: 36, id_driver: 23, id_driver_team: 3, start_pos: '15', end_pos: '14' },
    { id_race: 36, id_driver: 21, id_driver_team: 6, start_pos: '9', end_pos: '15' },
    { id_race: 36, id_driver: 16, id_driver_team: 3, start_pos: '13', end_pos: '16' },
    { id_race: 36, id_driver: 17, id_driver_team: 7, start_pos: '17', end_pos: '17' },
    { id_race: 36, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: '18' },
    { id_race: 36, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '19' },
    { id_race: 36, id_driver: 10, id_driver_team: 2, start_pos: '8', end_pos: '20' },
    { id_race: 37, id_driver: 20, id_driver_team: 8, start_pos: '14', end_pos: '1' },
    { id_race: 37, id_driver: 2, id_driver_team: 8, start_pos: '2', end_pos: '2' },
    { id_race: 37, id_driver: 5, id_driver_team: 1, start_pos: '1', end_pos: '3' },
    { id_race: 37, id_driver: 7, id_driver_team: 4, start_pos: '5', end_pos: '4' },
    { id_race: 37, id_driver: 3, id_driver_team: 10, start_pos: '3', end_pos: '5' },
    { id_race: 37, id_driver: 9, id_driver_team: 1, start_pos: '15', end_pos: '6' },
    { id_race: 37, id_driver: 11, id_driver_team: 10, start_pos: '16', end_pos: '7' },
    { id_race: 37, id_driver: 22, id_driver_team: 5, start_pos: '10', end_pos: '8' },
    { id_race: 37, id_driver: 13, id_driver_team: 9, start_pos: 'PL', end_pos: '9' },
    { id_race: 37, id_driver: 17, id_driver_team: 7, start_pos: '6', end_pos: '10' },
    { id_race: 37, id_driver: 6, id_driver_team: 5, start_pos: '9', end_pos: '11' },
    { id_race: 37, id_driver: 1, id_driver_team: 6, start_pos: '17', end_pos: '12' },
    { id_race: 37, id_driver: 15, id_driver_team: 9, start_pos: 'PL', end_pos: '13' },
    { id_race: 37, id_driver: 14, id_driver_team: 2, start_pos: '18', end_pos: '14' },
    { id_race: 37, id_driver: 21, id_driver_team: 6, start_pos: '7', end_pos: '15' },
    { id_race: 37, id_driver: 16, id_driver_team: 3, start_pos: '12', end_pos: '16' },
    { id_race: 37, id_driver: 23, id_driver_team: 3, start_pos: '19', end_pos: '17' },
    { id_race: 37, id_driver: 24, id_driver_team: 7, start_pos: '11', end_pos: '18' },
    { id_race: 37, id_driver: 10, id_driver_team: 2, start_pos: '13', end_pos: 'OUT' },
    { id_race: 37, id_driver: 4, id_driver_team: 4, start_pos: '4', end_pos: 'OUT' },
    { id_race: 38, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 38, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '2' },
    { id_race: 38, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '3' },
    { id_race: 38, id_driver: 4, id_driver_team: 4, start_pos: '4', end_pos: '4' },
    { id_race: 38, id_driver: 2, id_driver_team: 8, start_pos: '5', end_pos: '5' },
    { id_race: 38, id_driver: 3, id_driver_team: 10, start_pos: '13', end_pos: '6' },
    { id_race: 38, id_driver: 1, id_driver_team: 6, start_pos: '7', end_pos: '7' },
    { id_race: 38, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '8' },
    { id_race: 38, id_driver: 11, id_driver_team: 10, start_pos: '12', end_pos: '9' },
    { id_race: 38, id_driver: 6, id_driver_team: 5, start_pos: '10', end_pos: '10' },
    { id_race: 38, id_driver: 13, id_driver_team: 9, start_pos: '11', end_pos: '11' },
    { id_race: 38, id_driver: 17, id_driver_team: 7, start_pos: '15', end_pos: '12' },
    { id_race: 38, id_driver: 23, id_driver_team: 3, start_pos: '8', end_pos: '13' },
    { id_race: 38, id_driver: 22, id_driver_team: 5, start_pos: '19', end_pos: '14' },
    { id_race: 38, id_driver: 16, id_driver_team: 3, start_pos: '18', end_pos: '15' },
    { id_race: 38, id_driver: 14, id_driver_team: 2, start_pos: '14', end_pos: '16' },
    { id_race: 38, id_driver: 21, id_driver_team: 6, start_pos: '17', end_pos: '17' },
    { id_race: 38, id_driver: 24, id_driver_team: 7, start_pos: '20', end_pos: '18' },
    { id_race: 38, id_driver: 10, id_driver_team: 2, start_pos: '16', end_pos: 'OUT' },
    { id_race: 38, id_driver: 15, id_driver_team: 9, start_pos: '9', end_pos: 'OUT' },
    { id_race: 39, id_driver: 20, id_driver_team: 8, start_pos: '7', end_pos: '1' },
    { id_race: 39, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '2' },
    { id_race: 39, id_driver: 7, id_driver_team: 4, start_pos: '2', end_pos: '3' },
    { id_race: 39, id_driver: 5, id_driver_team: 1, start_pos: '18', end_pos: '4' },
    { id_race: 39, id_driver: 4, id_driver_team: 4, start_pos: '19', end_pos: '5' },
    { id_race: 39, id_driver: 2, id_driver_team: 8, start_pos: '13', end_pos: '6' },
    { id_race: 39, id_driver: 1, id_driver_team: 6, start_pos: '3', end_pos: '7' },
    { id_race: 39, id_driver: 13, id_driver_team: 9, start_pos: '5', end_pos: '8' },
    { id_race: 39, id_driver: 19, id_driver_team: 7, start_pos: '8', end_pos: '9' },
    { id_race: 39, id_driver: 14, id_driver_team: 2, start_pos: '9', end_pos: '10' },
    { id_race: 39, id_driver: 11, id_driver_team: 10, start_pos: '14', end_pos: '11' },
    { id_race: 39, id_driver: 23, id_driver_team: 3, start_pos: '17', end_pos: '12' },
    { id_race: 39, id_driver: 10, id_driver_team: 2, start_pos: '15', end_pos: '13' },
    { id_race: 39, id_driver: 15, id_driver_team: 9, start_pos: '20', end_pos: '14' },
    { id_race: 39, id_driver: 24, id_driver_team: 7, start_pos: '10', end_pos: '15' },
    { id_race: 39, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: '16' },
    { id_race: 39, id_driver: 21, id_driver_team: 6, start_pos: '4', end_pos: 'OUT' },
    { id_race: 39, id_driver: 6, id_driver_team: 5, start_pos: '12', end_pos: 'OUT' },
    { id_race: 39, id_driver: 3, id_driver_team: 10, start_pos: '6', end_pos: 'OUT' },
    { id_race: 39, id_driver: 22, id_driver_team: 5, start_pos: '11', end_pos: 'OUT' },
    { id_race: 40, id_driver: 2, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 40, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '2' },
    { id_race: 40, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '3' },
    { id_race: 40, id_driver: 1, id_driver_team: 6, start_pos: '6', end_pos: '4' },
    { id_race: 40, id_driver: 21, id_driver_team: 6, start_pos: '16', end_pos: '5' },
    { id_race: 40, id_driver: 6, id_driver_team: 5, start_pos: '11', end_pos: '6' },
    { id_race: 40, id_driver: 20, id_driver_team: 8, start_pos: '8', end_pos: '7' },
    { id_race: 40, id_driver: 22, id_driver_team: 5, start_pos: '13', end_pos: '8' },
    { id_race: 40, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '9' },
    { id_race: 40, id_driver: 13, id_driver_team: 9, start_pos: '7', end_pos: '10' },
    { id_race: 40, id_driver: 10, id_driver_team: 2, start_pos: '15', end_pos: '11' },
    { id_race: 40, id_driver: 16, id_driver_team: 3, start_pos: '9', end_pos: '12' },
    { id_race: 40, id_driver: 23, id_driver_team: 3, start_pos: '12', end_pos: '13' },
    { id_race: 40, id_driver: 7, id_driver_team: 4, start_pos: 'PL', end_pos: '14' },
    { id_race: 40, id_driver: 15, id_driver_team: 9, start_pos: '10', end_pos: 'OUT' },
    { id_race: 40, id_driver: 11, id_driver_team: 10, start_pos: '17', end_pos: 'OUT' },
    { id_race: 40, id_driver: 17, id_driver_team: 7, start_pos: '18', end_pos: 'OUT' },
    { id_race: 40, id_driver: 3, id_driver_team: 10, start_pos: '5', end_pos: 'OUT' },
    { id_race: 40, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: 'OUT' },
    { id_race: 40, id_driver: 14, id_driver_team: 2, start_pos: '14', end_pos: 'OUT' },
    { id_race: 41, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 41, id_driver: 2, id_driver_team: 8, start_pos: '4', end_pos: '2' },
    { id_race: 41, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '3' },
    { id_race: 41, id_driver: 11, id_driver_team: 10, start_pos: '5', end_pos: '4' },
    { id_race: 41, id_driver: 4, id_driver_team: 4, start_pos: '6', end_pos: '5' },
    { id_race: 41, id_driver: 22, id_driver_team: 5, start_pos: '9', end_pos: '6' },
    { id_race: 41, id_driver: 3, id_driver_team: 10, start_pos: '7', end_pos: '7' },
    { id_race: 41, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: '8' },
    { id_race: 41, id_driver: 24, id_driver_team: 7, start_pos: '19', end_pos: '9' },
    { id_race: 41, id_driver: 1, id_driver_team: 6, start_pos: '10', end_pos: '10' },
    { id_race: 41, id_driver: 21, id_driver_team: 6, start_pos: '11', end_pos: '11' },
    { id_race: 41, id_driver: 6, id_driver_team: 5, start_pos: '18', end_pos: '12' },
    { id_race: 41, id_driver: 15, id_driver_team: 9, start_pos: '13', end_pos: '13' },
    { id_race: 41, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '14' },
    { id_race: 41, id_driver: 10, id_driver_team: 2, start_pos: '12', end_pos: '15' },
    { id_race: 41, id_driver: 14, id_driver_team: 2, start_pos: '14', end_pos: '16' },
    { id_race: 41, id_driver: 23, id_driver_team: 3, start_pos: '15', end_pos: '17' },
    { id_race: 41, id_driver: 13, id_driver_team: 9, start_pos: 'PL', end_pos: '18' },
    { id_race: 41, id_driver: 17, id_driver_team: 7, start_pos: '16', end_pos: 'OUT' },
    { id_race: 41, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: 'OUT' },
    { id_race: 42, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 42, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '2' },
    { id_race: 42, id_driver: 9, id_driver_team: 1, start_pos: '12', end_pos: '3' },
    { id_race: 42, id_driver: 2, id_driver_team: 8, start_pos: '9', end_pos: '4' },
    { id_race: 42, id_driver: 7, id_driver_team: 4, start_pos: '4', end_pos: '5' },
    { id_race: 42, id_driver: 1, id_driver_team: 6, start_pos: '6', end_pos: '6' },
    { id_race: 42, id_driver: 22, id_driver_team: 5, start_pos: '10', end_pos: '7' },
    { id_race: 42, id_driver: 16, id_driver_team: 3, start_pos: '13', end_pos: '8' },
    { id_race: 42, id_driver: 15, id_driver_team: 9, start_pos: '19', end_pos: '9' },
    { id_race: 42, id_driver: 11, id_driver_team: 10, start_pos: 'PL', end_pos: '10' },
    { id_race: 42, id_driver: 14, id_driver_team: 2, start_pos: '18', end_pos: '11' },
    { id_race: 42, id_driver: 17, id_driver_team: 7, start_pos: '8', end_pos: '12' },
    { id_race: 42, id_driver: 13, id_driver_team: 9, start_pos: '11', end_pos: '13' },
    { id_race: 42, id_driver: 23, id_driver_team: 3, start_pos: '16', end_pos: '14' },
    { id_race: 42, id_driver: 3, id_driver_team: 10, start_pos: '14', end_pos: '15' },
    { id_race: 42, id_driver: 21, id_driver_team: 6, start_pos: '15', end_pos: '16' },
    { id_race: 42, id_driver: 24, id_driver_team: 7, start_pos: '17', end_pos: '17' },
    { id_race: 42, id_driver: 6, id_driver_team: 5, start_pos: '5', end_pos: 'OUT' },
    { id_race: 42, id_driver: 10, id_driver_team: 2, start_pos: '7', end_pos: 'OUT' },
    { id_race: 42, id_driver: 5, id_driver_team: 1, start_pos: '1', end_pos: 'OUT' },
    { id_race: 43, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 43, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '2' },
    { id_race: 43, id_driver: 2, id_driver_team: 8, start_pos: '4', end_pos: '3' },
    { id_race: 43, id_driver: 7, id_driver_team: 4, start_pos: '2', end_pos: '4' },
    { id_race: 43, id_driver: 5, id_driver_team: 1, start_pos: '5', end_pos: '5' },
    { id_race: 43, id_driver: 9, id_driver_team: 1, start_pos: '7', end_pos: '6' },
    { id_race: 43, id_driver: 21, id_driver_team: 6, start_pos: '11', end_pos: '7' },
    { id_race: 43, id_driver: 11, id_driver_team: 10, start_pos: '10', end_pos: '8' },
    { id_race: 43, id_driver: 1, id_driver_team: 6, start_pos: '8', end_pos: '9' },
    { id_race: 43, id_driver: 10, id_driver_team: 2, start_pos: '6', end_pos: '10' },
    { id_race: 43, id_driver: 13, id_driver_team: 9, start_pos: '14', end_pos: '11' },
    { id_race: 43, id_driver: 17, id_driver_team: 7, start_pos: '17', end_pos: '12' },
    { id_race: 43, id_driver: 14, id_driver_team: 2, start_pos: '12', end_pos: '13' },
    { id_race: 43, id_driver: 22, id_driver_team: 5, start_pos: '16', end_pos: '14' },
    { id_race: 43, id_driver: 6, id_driver_team: 5, start_pos: '20', end_pos: '15' },
    { id_race: 43, id_driver: 23, id_driver_team: 3, start_pos: '15', end_pos: '16' },
    { id_race: 43, id_driver: 16, id_driver_team: 3, start_pos: '19', end_pos: '17' },
    { id_race: 43, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: '18' },
    { id_race: 43, id_driver: 3, id_driver_team: 10, start_pos: '9', end_pos: '19' },
    { id_race: 43, id_driver: 15, id_driver_team: 9, start_pos: '13', end_pos: 'OUT' },
    { id_race: 44, id_driver: 7, id_driver_team: 4, start_pos: '1', end_pos: '1' },
    { id_race: 44, id_driver: 4, id_driver_team: 4, start_pos: '2', end_pos: '2' },
    { id_race: 44, id_driver: 5, id_driver_team: 1, start_pos: '7', end_pos: '3' },
    { id_race: 44, id_driver: 9, id_driver_team: 1, start_pos: '5', end_pos: '4' },
    { id_race: 44, id_driver: 3, id_driver_team: 10, start_pos: '17', end_pos: '5' },
    { id_race: 44, id_driver: 20, id_driver_team: 8, start_pos: '3', end_pos: '6' },
    { id_race: 44, id_driver: 2, id_driver_team: 8, start_pos: '4', end_pos: '7' },
    { id_race: 44, id_driver: 11, id_driver_team: 10, start_pos: '16', end_pos: '8' },
    { id_race: 44, id_driver: 10, id_driver_team: 2, start_pos: '14', end_pos: '9' },
    { id_race: 44, id_driver: 6, id_driver_team: 5, start_pos: '15', end_pos: '10' },
    { id_race: 44, id_driver: 22, id_driver_team: 5, start_pos: '9', end_pos: '11' },
    { id_race: 44, id_driver: 14, id_driver_team: 2, start_pos: '13', end_pos: '12' },
    { id_race: 44, id_driver: 23, id_driver_team: 3, start_pos: '12', end_pos: '13' },
    { id_race: 44, id_driver: 13, id_driver_team: 9, start_pos: '10', end_pos: '14' },
    { id_race: 44, id_driver: 17, id_driver_team: 7, start_pos: '19', end_pos: '15' },
    { id_race: 44, id_driver: 24, id_driver_team: 7, start_pos: '18', end_pos: '16' },
    { id_race: 44, id_driver: 15, id_driver_team: 9, start_pos: 'PL', end_pos: '17' },
    { id_race: 44, id_driver: 1, id_driver_team: 6, start_pos: '6', end_pos: 'OUT' },
    { id_race: 44, id_driver: 16, id_driver_team: 3, start_pos: '8', end_pos: 'OUT' },
    { id_race: 44, id_driver: 21, id_driver_team: 6, start_pos: '11', end_pos: 'OUT' },
    { id_race: 45, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 45, id_driver: 9, id_driver_team: 1, start_pos: '3', end_pos: '2' },
    { id_race: 45, id_driver: 2, id_driver_team: 8, start_pos: '2', end_pos: '3' },
    { id_race: 45, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '4' },
    { id_race: 45, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '5' },
    { id_race: 45, id_driver: 1, id_driver_team: 6, start_pos: '7', end_pos: '6' },
    { id_race: 45, id_driver: 11, id_driver_team: 10, start_pos: '8', end_pos: '7' },
    { id_race: 45, id_driver: 6, id_driver_team: 5, start_pos: '14', end_pos: '8' },
    { id_race: 45, id_driver: 21, id_driver_team: 6, start_pos: '13', end_pos: '9' },
    { id_race: 45, id_driver: 22, id_driver_team: 5, start_pos: '9', end_pos: '10' },
    { id_race: 45, id_driver: 15, id_driver_team: 9, start_pos: '11', end_pos: '11' },
    { id_race: 45, id_driver: 14, id_driver_team: 2, start_pos: '15', end_pos: '12' },
    { id_race: 45, id_driver: 17, id_driver_team: 7, start_pos: '19', end_pos: '13' },
    { id_race: 45, id_driver: 13, id_driver_team: 9, start_pos: '17', end_pos: '14' },
    { id_race: 45, id_driver: 10, id_driver_team: 2, start_pos: '18', end_pos: '15' },
    { id_race: 45, id_driver: 23, id_driver_team: 3, start_pos: '12', end_pos: '16' },
    { id_race: 45, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: '17' },
    { id_race: 45, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '18' },
    { id_race: 45, id_driver: 24, id_driver_team: 7, start_pos: '20', end_pos: '19' },
    { id_race: 45, id_driver: 3, id_driver_team: 10, start_pos: '10', end_pos: 'OUT' },
    { id_race: 4, id_driver: 2, id_driver_team: 8, start_pos: '3', end_pos: '1' },
    { id_race: 4, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '2' },
    { id_race: 4, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '3' },
    { id_race: 4, id_driver: 3, id_driver_team: 5, start_pos: '6', end_pos: '4' },
    { id_race: 4, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '5' },
    { id_race: 4, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '6' },
    { id_race: 4, id_driver: 6, id_driver_team: 5, start_pos: '9', end_pos: '7' },
    { id_race: 4, id_driver: 7, id_driver_team: 4, start_pos: '11', end_pos: '8' },
    { id_race: 4, id_driver: 1, id_driver_team: 5, start_pos: '7', end_pos: '9' },
    { id_race: 4, id_driver: 15, id_driver_team: 9, start_pos: '8', end_pos: '10' },
    { id_race: 4, id_driver: 12, id_driver_team: 6, start_pos: '10', end_pos: '11' },
    { id_race: 4, id_driver: 17, id_driver_team: 7, start_pos: '12', end_pos: '12' },
    { id_race: 4, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: '13' },
    { id_race: 4, id_driver: 13, id_driver_team: 10, start_pos: '17', end_pos: '14' },
    { id_race: 4, id_driver: 11, id_driver_team: 10, start_pos: '19', end_pos: '15' },
    { id_race: 4, id_driver: 18, id_driver_team: 7, start_pos: '14', end_pos: '16' },
    { id_race: 4, id_driver: 8, id_driver_team: 3, start_pos: '20', end_pos: '17' },
    { id_race: 4, id_driver: 10, id_driver_team: 2, start_pos: '13', end_pos: '18' },
    { id_race: 4, id_driver: 14, id_driver_team: 2, start_pos: '15', end_pos: 'OUT' },
    { id_race: 4, id_driver: 19, id_driver_team: 9, start_pos: '18', end_pos: 'OUT' },
    { id_race: 5, id_driver: 20, id_driver_team: 8, start_pos: '9', end_pos: '1' },
    { id_race: 5, id_driver: 2, id_driver_team: 8, start_pos: '1', end_pos: '2' },
    { id_race: 5, id_driver: 3, id_driver_team: 5, start_pos: '2', end_pos: '3' },
    { id_race: 5, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '4' },
    { id_race: 5, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '5' },
    { id_race: 5, id_driver: 4, id_driver_team: 4, start_pos: '13', end_pos: '6' },
    { id_race: 5, id_driver: 9, id_driver_team: 1, start_pos: '7', end_pos: '7' },
    { id_race: 5, id_driver: 13, id_driver_team: 10, start_pos: '5', end_pos: '8' },
    { id_race: 5, id_driver: 11, id_driver_team: 10, start_pos: '8', end_pos: '9' },
    { id_race: 5, id_driver: 16, id_driver_team: 3, start_pos: '4', end_pos: '10' },
    { id_race: 5, id_driver: 15, id_driver_team: 9, start_pos: '17', end_pos: '11' },
    { id_race: 5, id_driver: 6, id_driver_team: 5, start_pos: '18', end_pos: '12' },
    { id_race: 5, id_driver: 10, id_driver_team: 2, start_pos: '10', end_pos: '13' },
    { id_race: 5, id_driver: 17, id_driver_team: 7, start_pos: '11', end_pos: '14' },
    { id_race: 5, id_driver: 8, id_driver_team: 3, start_pos: '12', end_pos: '15' },
    { id_race: 5, id_driver: 14, id_driver_team: 2, start_pos: '14', end_pos: '16' },
    { id_race: 5, id_driver: 1, id_driver_team: 6, start_pos: '16', end_pos: '17' },
    { id_race: 5, id_driver: 19, id_driver_team: 9, start_pos: '15', end_pos: '18' },
    { id_race: 5, id_driver: 12, id_driver_team: 6, start_pos: '19', end_pos: '19' },
    { id_race: 5, id_driver: 18, id_driver_team: 7, start_pos: '20', end_pos: '20' },
    { id_race: 7, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 7, id_driver: 3, id_driver_team: 5, start_pos: '2', end_pos: '2' },
    { id_race: 7, id_driver: 11, id_driver_team: 10, start_pos: '3', end_pos: '3' },
    { id_race: 7, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '4' },
    { id_race: 7, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: '5' },
    { id_race: 7, id_driver: 9, id_driver_team: 1, start_pos: '6', end_pos: '6' },
    { id_race: 7, id_driver: 13, id_driver_team: 10, start_pos: '7', end_pos: '7' },
    { id_race: 7, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '8' },
    { id_race: 7, id_driver: 1, id_driver_team: 6, start_pos: '10', end_pos: '9' },
    { id_race: 7, id_driver: 12, id_driver_team: 6, start_pos: '11', end_pos: '10' },
    { id_race: 7, id_driver: 10, id_driver_team: 2, start_pos: '15', end_pos: '11' },
    { id_race: 7, id_driver: 19, id_driver_team: 9, start_pos: '12', end_pos: '12' },
    { id_race: 7, id_driver: 14, id_driver_team: 2, start_pos: '19', end_pos: '13' },
    { id_race: 7, id_driver: 17, id_driver_team: 7, start_pos: '13', end_pos: '14' },
    { id_race: 7, id_driver: 15, id_driver_team: 9, start_pos: '9', end_pos: '15' },
    { id_race: 7, id_driver: 2, id_driver_team: 8, start_pos: '20', end_pos: '16' },
    { id_race: 7, id_driver: 8, id_driver_team: 3, start_pos: '18', end_pos: '17' },
    { id_race: 7, id_driver: 18, id_driver_team: 7, start_pos: '16', end_pos: '18' },
    { id_race: 7, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '19' },
    { id_race: 7, id_driver: 6, id_driver_team: 5, start_pos: '14', end_pos: 'OUT' },
    { id_race: 8, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 8, id_driver: 4, id_driver_team: 4, start_pos: '4', end_pos: '2' },
    { id_race: 8, id_driver: 7, id_driver_team: 4, start_pos: '12', end_pos: '3' },
    { id_race: 8, id_driver: 2, id_driver_team: 8, start_pos: '11', end_pos: '4' },
    { id_race: 8, id_driver: 5, id_driver_team: 1, start_pos: '2', end_pos: '5' },
    { id_race: 8, id_driver: 6, id_driver_team: 5, start_pos: '5', end_pos: '6' },
    { id_race: 8, id_driver: 3, id_driver_team: 5, start_pos: '8', end_pos: '7' },
    { id_race: 8, id_driver: 11, id_driver_team: 10, start_pos: '6', end_pos: '8' },
    { id_race: 8, id_driver: 14, id_driver_team: 2, start_pos: '13', end_pos: '9' },
    { id_race: 8, id_driver: 13, id_driver_team: 10, start_pos: '10', end_pos: '10' },
    { id_race: 8, id_driver: 9, id_driver_team: 1, start_pos: '19', end_pos: '11' },
    { id_race: 8, id_driver: 15, id_driver_team: 9, start_pos: '15', end_pos: '12' },
    { id_race: 8, id_driver: 12, id_driver_team: 6, start_pos: '9', end_pos: '13' },
    { id_race: 8, id_driver: 19, id_driver_team: 9, start_pos: '14', end_pos: '14' },
    { id_race: 8, id_driver: 8, id_driver_team: 3, start_pos: '7', end_pos: '15' },
    { id_race: 8, id_driver: 17, id_driver_team: 7, start_pos: '18', end_pos: '16' },
    { id_race: 8, id_driver: 1, id_driver_team: 6, start_pos: '3', end_pos: '17' },
    { id_race: 8, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '18' },
    { id_race: 8, id_driver: 10, id_driver_team: 2, start_pos: '16', end_pos: '19' },
    { id_race: 8, id_driver: 18, id_driver_team: 7, start_pos: '20', end_pos: '20' },
    { id_race: 9, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 9, id_driver: 3, id_driver_team: 5, start_pos: '2', end_pos: '2' },
    { id_race: 9, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '3' },
    { id_race: 9, id_driver: 9, id_driver_team: 1, start_pos: '10', end_pos: '4' },
    { id_race: 9, id_driver: 5, id_driver_team: 1, start_pos: '11', end_pos: '5' },
    { id_race: 9, id_driver: 2, id_driver_team: 8, start_pos: '12', end_pos: '6' },
    { id_race: 9, id_driver: 17, id_driver_team: 7, start_pos: '9', end_pos: '7' },
    { id_race: 9, id_driver: 11, id_driver_team: 10, start_pos: '6', end_pos: '8' },
    { id_race: 9, id_driver: 6, id_driver_team: 5, start_pos: '16', end_pos: '9' },
    { id_race: 9, id_driver: 10, id_driver_team: 2, start_pos: '14', end_pos: '10' },
    { id_race: 9, id_driver: 12, id_driver_team: 6, start_pos: '8', end_pos: '11' },
    { id_race: 9, id_driver: 13, id_driver_team: 10, start_pos: '15', end_pos: '12' },
    { id_race: 9, id_driver: 1, id_driver_team: 6, start_pos: '7', end_pos: '13' },
    { id_race: 9, id_driver: 15, id_driver_team: 9, start_pos: '19', end_pos: '14' },
    { id_race: 9, id_driver: 8, id_driver_team: 3, start_pos: '5', end_pos: '15' },
    { id_race: 9, id_driver: 14, id_driver_team: 2, start_pos: '20', end_pos: '16' },
    { id_race: 9, id_driver: 16, id_driver_team: 3, start_pos: '13', end_pos: '17' },
    { id_race: 9, id_driver: 19, id_driver_team: 9, start_pos: '17', end_pos: '18' },
    { id_race: 9, id_driver: 7, id_driver_team: 4, start_pos: '4', end_pos: 'OUT' },
    { id_race: 9, id_driver: 18, id_driver_team: 7, start_pos: '18', end_pos: 'OUT' },
    { id_race: 10, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 10, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '2' },
    { id_race: 10, id_driver: 2, id_driver_team: 8, start_pos: '15', end_pos: '3' },
    { id_race: 10, id_driver: 1, id_driver_team: 6, start_pos: '4', end_pos: '4' },
    { id_race: 10, id_driver: 3, id_driver_team: 5, start_pos: '7', end_pos: '5' },
    { id_race: 10, id_driver: 5, id_driver_team: 1, start_pos: '3', end_pos: '6' },
    { id_race: 10, id_driver: 7, id_driver_team: 4, start_pos: '11', end_pos: '7' },
    { id_race: 10, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '8' },
    { id_race: 10, id_driver: 6, id_driver_team: 5, start_pos: '6', end_pos: '9' },
    { id_race: 10, id_driver: 13, id_driver_team: 10, start_pos: '9', end_pos: '10' },
    { id_race: 10, id_driver: 17, id_driver_team: 7, start_pos: '10', end_pos: '11' },
    { id_race: 10, id_driver: 14, id_driver_team: 2, start_pos: '17', end_pos: '12' },
    { id_race: 10, id_driver: 18, id_driver_team: 7, start_pos: '18', end_pos: '13' },
    { id_race: 10, id_driver: 11, id_driver_team: 10, start_pos: '12', end_pos: '14' },
    { id_race: 10, id_driver: 10, id_driver_team: 2, start_pos: '14', end_pos: '15' },
    { id_race: 10, id_driver: 12, id_driver_team: 6, start_pos: '13', end_pos: '16' },
    { id_race: 10, id_driver: 19, id_driver_team: 9, start_pos: '20', end_pos: '17' },
    { id_race: 10, id_driver: 16, id_driver_team: 3, start_pos: '19', end_pos: '18' },
    { id_race: 10, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '19' },
    { id_race: 10, id_driver: 8, id_driver_team: 3, start_pos: '8', end_pos: 'OUT' },
    { id_race: 11, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 11, id_driver: 1, id_driver_team: 6, start_pos: '2', end_pos: '2' },
    { id_race: 11, id_driver: 4, id_driver_team: 4, start_pos: '7', end_pos: '3' },
    { id_race: 11, id_driver: 12, id_driver_team: 6, start_pos: '3', end_pos: '4' },
    { id_race: 11, id_driver: 7, id_driver_team: 4, start_pos: '6', end_pos: '5' },
    { id_race: 11, id_driver: 2, id_driver_team: 8, start_pos: '15', end_pos: '6' },
    { id_race: 11, id_driver: 3, id_driver_team: 5, start_pos: '9', end_pos: '7' },
    { id_race: 11, id_driver: 17, id_driver_team: 7, start_pos: '8', end_pos: '8' },
    { id_race: 11, id_driver: 9, id_driver_team: 1, start_pos: '4', end_pos: '9' },
    { id_race: 11, id_driver: 5, id_driver_team: 1, start_pos: '5', end_pos: '10' },
    { id_race: 11, id_driver: 18, id_driver_team: 7, start_pos: '14', end_pos: '11' },
    { id_race: 11, id_driver: 10, id_driver_team: 2, start_pos: '20', end_pos: '12' },
    { id_race: 11, id_driver: 8, id_driver_team: 3, start_pos: '11', end_pos: '13' },
    { id_race: 11, id_driver: 6, id_driver_team: 5, start_pos: '12', end_pos: '14' },
    { id_race: 11, id_driver: 14, id_driver_team: 2, start_pos: '17', end_pos: '15' },
    { id_race: 11, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '16' },
    { id_race: 11, id_driver: 19, id_driver_team: 9, start_pos: '18', end_pos: '17' },
    { id_race: 11, id_driver: 13, id_driver_team: 10, start_pos: '10', end_pos: 'OUT' },
    { id_race: 11, id_driver: 16, id_driver_team: 3, start_pos: '19', end_pos: 'OUT' },
    { id_race: 11, id_driver: 11, id_driver_team: 10, start_pos: '13', end_pos: 'OUT' },
    { id_race: 12, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 12, id_driver: 1, id_driver_team: 6, start_pos: '3', end_pos: '2' },
    { id_race: 12, id_driver: 2, id_driver_team: 8, start_pos: '9', end_pos: '3' },
    { id_race: 12, id_driver: 4, id_driver_team: 4, start_pos: '1', end_pos: '4' },
    { id_race: 12, id_driver: 12, id_driver_team: 6, start_pos: '4', end_pos: '5' },
    { id_race: 12, id_driver: 7, id_driver_team: 4, start_pos: '18', end_pos: '6' },
    { id_race: 12, id_driver: 9, id_driver_team: 1, start_pos: '6', end_pos: '7' },
    { id_race: 12, id_driver: 5, id_driver_team: 1, start_pos: '11', end_pos: '8' },
    { id_race: 12, id_driver: 3, id_driver_team: 5, start_pos: '8', end_pos: '9' },
    { id_race: 12, id_driver: 6, id_driver_team: 5, start_pos: '14', end_pos: '10' },
    { id_race: 12, id_driver: 17, id_driver_team: 7, start_pos: '16', end_pos: '11' },
    { id_race: 12, id_driver: 10, id_driver_team: 2, start_pos: '7', end_pos: '12' },
    { id_race: 12, id_driver: 21, id_driver_team: 9, start_pos: '13', end_pos: '13' },
    { id_race: 12, id_driver: 8, id_driver_team: 3, start_pos: '10', end_pos: '14' },
    { id_race: 12, id_driver: 15, id_driver_team: 9, start_pos: '17', end_pos: '15' },
    { id_race: 12, id_driver: 14, id_driver_team: 2, start_pos: '5', end_pos: '16' },
    { id_race: 12, id_driver: 16, id_driver_team: 3, start_pos: '19', end_pos: '17' },
    { id_race: 12, id_driver: 18, id_driver_team: 7, start_pos: '20', end_pos: 'OUT' },
    { id_race: 12, id_driver: 11, id_driver_team: 10, start_pos: '12', end_pos: 'OUT' },
    { id_race: 12, id_driver: 13, id_driver_team: 10, start_pos: '15', end_pos: 'OUT' },
    { id_race: 13, id_driver: 20, id_driver_team: 8, start_pos: '6', end_pos: '1' },
    { id_race: 13, id_driver: 2, id_driver_team: 8, start_pos: '2', end_pos: '2' },
    { id_race: 13, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '3' },
    { id_race: 13, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '4' },
    { id_race: 13, id_driver: 3, id_driver_team: 5, start_pos: '9', end_pos: '5' },
    { id_race: 13, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: '6' },
    { id_race: 13, id_driver: 1, id_driver_team: 6, start_pos: '7', end_pos: '7' },
    { id_race: 13, id_driver: 11, id_driver_team: 10, start_pos: '14', end_pos: '8' },
    { id_race: 13, id_driver: 6, id_driver_team: 5, start_pos: '10', end_pos: '9' },
    { id_race: 13, id_driver: 15, id_driver_team: 9, start_pos: '11', end_pos: '10' },
    { id_race: 13, id_driver: 13, id_driver_team: 10, start_pos: '12', end_pos: '11' },
    { id_race: 13, id_driver: 10, id_driver_team: 2, start_pos: '13', end_pos: '12' },
    { id_race: 13, id_driver: 14, id_driver_team: 2, start_pos: '17', end_pos: '13' },
    { id_race: 13, id_driver: 17, id_driver_team: 7, start_pos: '15', end_pos: '14' },
    { id_race: 13, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: '15' },
    { id_race: 13, id_driver: 21, id_driver_team: 9, start_pos: '19', end_pos: '16' },
    { id_race: 13, id_driver: 18, id_driver_team: 7, start_pos: '18', end_pos: '17' },
    { id_race: 13, id_driver: 8, id_driver_team: 3, start_pos: '20', end_pos: '18' },
    { id_race: 13, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: 'OUT' },
    { id_race: 13, id_driver: 12, id_driver_team: 6, start_pos: '5', end_pos: 'OUT' },
    { id_race: 14, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 14, id_driver: 3, id_driver_team: 5, start_pos: '5', end_pos: '2' },
    { id_race: 14, id_driver: 13, id_driver_team: 10, start_pos: '12', end_pos: '3' },
    { id_race: 14, id_driver: 2, id_driver_team: 8, start_pos: '7', end_pos: '4' },
    { id_race: 14, id_driver: 5, id_driver_team: 1, start_pos: '6', end_pos: '5' },
    { id_race: 14, id_driver: 4, id_driver_team: 4, start_pos: '13', end_pos: '6' },
    { id_race: 14, id_driver: 1, id_driver_team: 6, start_pos: '2', end_pos: '7' },
    { id_race: 14, id_driver: 17, id_driver_team: 7, start_pos: '4', end_pos: '8' },
    { id_race: 14, id_driver: 12, id_driver_team: 6, start_pos: '8', end_pos: '9' },
    { id_race: 14, id_driver: 11, id_driver_team: 10, start_pos: '16', end_pos: '10' },
    { id_race: 14, id_driver: 6, id_driver_team: 5, start_pos: '11', end_pos: '11' },
    { id_race: 14, id_driver: 8, id_driver_team: 3, start_pos: '14', end_pos: '12' },
    { id_race: 14, id_driver: 25, id_driver_team: 9, start_pos: '19', end_pos: '13' },
    { id_race: 14, id_driver: 10, id_driver_team: 2, start_pos: '18', end_pos: '14' },
    { id_race: 14, id_driver: 15, id_driver_team: 9, start_pos: '17', end_pos: '15' },
    { id_race: 14, id_driver: 16, id_driver_team: 3, start_pos: '20', end_pos: '16' },
    { id_race: 14, id_driver: 7, id_driver_team: 4, start_pos: '3', end_pos: '17' },
    { id_race: 14, id_driver: 14, id_driver_team: 2, start_pos: '15', end_pos: 'OUT' },
    { id_race: 14, id_driver: 9, id_driver_team: 1, start_pos: '9', end_pos: 'OUT' },
    { id_race: 14, id_driver: 18, id_driver_team: 7, start_pos: '10', end_pos: 'OUT' },
    { id_race: 15, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 15, id_driver: 2, id_driver_team: 8, start_pos: '5', end_pos: '2' },
    { id_race: 15, id_driver: 5, id_driver_team: 1, start_pos: '1', end_pos: '3' },
    { id_race: 15, id_driver: 9, id_driver_team: 1, start_pos: '3', end_pos: '4' },
    { id_race: 15, id_driver: 7, id_driver_team: 4, start_pos: '4', end_pos: '5' },
    { id_race: 15, id_driver: 4, id_driver_team: 4, start_pos: '8', end_pos: '6' },
    { id_race: 15, id_driver: 17, id_driver_team: 7, start_pos: '6', end_pos: '7' },
    { id_race: 15, id_driver: 1, id_driver_team: 6, start_pos: '9', end_pos: '8' },
    { id_race: 15, id_driver: 3, id_driver_team: 5, start_pos: '10', end_pos: '9' },
    { id_race: 15, id_driver: 10, id_driver_team: 2, start_pos: '14', end_pos: '10' },
    { id_race: 15, id_driver: 25, id_driver_team: 9, start_pos: '12', end_pos: '11' },
    { id_race: 15, id_driver: 12, id_driver_team: 6, start_pos: '7', end_pos: '12' },
    { id_race: 15, id_driver: 18, id_driver_team: 7, start_pos: '15', end_pos: '13' },
    { id_race: 15, id_driver: 14, id_driver_team: 2, start_pos: '16', end_pos: '14' },
    { id_race: 15, id_driver: 13, id_driver_team: 10, start_pos: '17', end_pos: '15' },
    { id_race: 15, id_driver: 6, id_driver_team: 5, start_pos: '20', end_pos: '16' },
    { id_race: 15, id_driver: 8, id_driver_team: 3, start_pos: '13', end_pos: '17' },
    { id_race: 15, id_driver: 16, id_driver_team: 3, start_pos: '19', end_pos: '18' },
    { id_race: 15, id_driver: 11, id_driver_team: 10, start_pos: '18', end_pos: 'OUT' },
    { id_race: 15, id_driver: 15, id_driver_team: 9, start_pos: '11', end_pos: 'OUT' },
    { id_race: 16, id_driver: 5, id_driver_team: 1, start_pos: '1', end_pos: '1' },
    { id_race: 16, id_driver: 1, id_driver_team: 6, start_pos: '4', end_pos: '2' },
    { id_race: 16, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '3' },
    { id_race: 16, id_driver: 9, id_driver_team: 1, start_pos: '3', end_pos: '4' },
    { id_race: 16, id_driver: 20, id_driver_team: 8, start_pos: '11', end_pos: '5' },
    { id_race: 16, id_driver: 13, id_driver_team: 10, start_pos: '12', end_pos: '6' },
    { id_race: 16, id_driver: 12, id_driver_team: 6, start_pos: '17', end_pos: '7' },
    { id_race: 16, id_driver: 2, id_driver_team: 8, start_pos: '13', end_pos: '8' },
    { id_race: 16, id_driver: 25, id_driver_team: 9, start_pos: '10', end_pos: '9' },
    { id_race: 16, id_driver: 16, id_driver_team: 3, start_pos: '6', end_pos: '10' },
    { id_race: 16, id_driver: 17, id_driver_team: 7, start_pos: '14', end_pos: '11' },
    { id_race: 16, id_driver: 14, id_driver_team: 2, start_pos: '19', end_pos: '12' },
    { id_race: 16, id_driver: 8, id_driver_team: 3, start_pos: '9', end_pos: '13' },
    { id_race: 16, id_driver: 18, id_driver_team: 7, start_pos: '18', end_pos: '14' },
    { id_race: 16, id_driver: 3, id_driver_team: 5, start_pos: '7', end_pos: '15' },
    { id_race: 16, id_driver: 7, id_driver_team: 4, start_pos: '2', end_pos: '16' },
    { id_race: 16, id_driver: 10, id_driver_team: 2, start_pos: '16', end_pos: 'OUT' },
    { id_race: 16, id_driver: 11, id_driver_team: 10, start_pos: '8', end_pos: 'OUT' },
    { id_race: 16, id_driver: 15, id_driver_team: 9, start_pos: '15', end_pos: 'OUT' },
    { id_race: 16, id_driver: 6, id_driver_team: 5, start_pos: '20', end_pos: 'OUT' },
    { id_race: 17, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 17, id_driver: 1, id_driver_team: 6, start_pos: '3', end_pos: '2' },
    { id_race: 17, id_driver: 12, id_driver_team: 6, start_pos: '2', end_pos: '3' },
    { id_race: 17, id_driver: 9, id_driver_team: 1, start_pos: '4', end_pos: '4' },
    { id_race: 17, id_driver: 4, id_driver_team: 4, start_pos: '7', end_pos: '5' },
    { id_race: 17, id_driver: 5, id_driver_team: 1, start_pos: '6', end_pos: '6' },
    { id_race: 17, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: '7' },
    { id_race: 17, id_driver: 3, id_driver_team: 5, start_pos: '10', end_pos: '8' },
    { id_race: 17, id_driver: 11, id_driver_team: 10, start_pos: '14', end_pos: '9' },
    { id_race: 17, id_driver: 13, id_driver_team: 10, start_pos: '12', end_pos: '10' },
    { id_race: 17, id_driver: 25, id_driver_team: 9, start_pos: '11', end_pos: '11' },
    { id_race: 17, id_driver: 15, id_driver_team: 9, start_pos: '9', end_pos: '12' },
    { id_race: 17, id_driver: 14, id_driver_team: 2, start_pos: '19', end_pos: '13' },
    { id_race: 17, id_driver: 8, id_driver_team: 3, start_pos: '18', end_pos: '14' },
    { id_race: 17, id_driver: 16, id_driver_team: 3, start_pos: '15', end_pos: '15' },
    { id_race: 17, id_driver: 17, id_driver_team: 7, start_pos: '13', end_pos: 'OUT' },
    { id_race: 17, id_driver: 18, id_driver_team: 7, start_pos: '20', end_pos: 'OUT' },
    { id_race: 17, id_driver: 6, id_driver_team: 5, start_pos: '17', end_pos: 'OUT' },
    { id_race: 17, id_driver: 2, id_driver_team: 8, start_pos: '5', end_pos: 'OUT' },
    { id_race: 17, id_driver: 10, id_driver_team: 2, start_pos: '16', end_pos: 'OUT' },
    { id_race: 18, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 18, id_driver: 12, id_driver_team: 6, start_pos: '6', end_pos: '2' },
    { id_race: 18, id_driver: 1, id_driver_team: 6, start_pos: '10', end_pos: '3' },
    { id_race: 18, id_driver: 7, id_driver_team: 4, start_pos: '2', end_pos: '4' },
    { id_race: 18, id_driver: 9, id_driver_team: 1, start_pos: '5', end_pos: '5' },
    { id_race: 18, id_driver: 3, id_driver_team: 5, start_pos: '4', end_pos: '6' },
    { id_race: 18, id_driver: 11, id_driver_team: 10, start_pos: '8', end_pos: '7' },
    { id_race: 18, id_driver: 10, id_driver_team: 2, start_pos: '9', end_pos: '8' },
    { id_race: 18, id_driver: 14, id_driver_team: 2, start_pos: '19', end_pos: '9' },
    { id_race: 18, id_driver: 2, id_driver_team: 8, start_pos: '20', end_pos: '10' },
    { id_race: 18, id_driver: 6, id_driver_team: 5, start_pos: '16', end_pos: '11' },
    { id_race: 18, id_driver: 13, id_driver_team: 10, start_pos: '7', end_pos: '12' },
    { id_race: 18, id_driver: 17, id_driver_team: 7, start_pos: '13', end_pos: '13' },
    { id_race: 18, id_driver: 16, id_driver_team: 3, start_pos: '18', end_pos: '14' },
    { id_race: 18, id_driver: 15, id_driver_team: 9, start_pos: '11', end_pos: '15' },
    { id_race: 18, id_driver: 8, id_driver_team: 3, start_pos: '14', end_pos: '16' },
    { id_race: 18, id_driver: 25, id_driver_team: 9, start_pos: '17', end_pos: '17' },
    { id_race: 18, id_driver: 18, id_driver_team: 7, start_pos: '15', end_pos: 'OUT' },
    { id_race: 18, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: 'OUT' },
    { id_race: 18, id_driver: 5, id_driver_team: 1, start_pos: '12', end_pos: 'OUT' },
    { id_race: 19, id_driver: 20, id_driver_team: 8, start_pos: '6', end_pos: '1' },
    { id_race: 19, id_driver: 4, id_driver_team: 4, start_pos: '3', end_pos: '2' },
    { id_race: 19, id_driver: 1, id_driver_team: 6, start_pos: '2', end_pos: '3' },
    { id_race: 19, id_driver: 5, id_driver_team: 1, start_pos: '4', end_pos: '4' },
    { id_race: 19, id_driver: 2, id_driver_team: 8, start_pos: '9', end_pos: '5' },
    { id_race: 19, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '6' },
    { id_race: 19, id_driver: 7, id_driver_team: 4, start_pos: '5', end_pos: '7' },
    { id_race: 19, id_driver: 13, id_driver_team: 10, start_pos: '7', end_pos: '8' },
    { id_race: 19, id_driver: 6, id_driver_team: 5, start_pos: '20', end_pos: '9' },
    { id_race: 19, id_driver: 15, id_driver_team: 9, start_pos: '11', end_pos: '10' },
    { id_race: 19, id_driver: 17, id_driver_team: 7, start_pos: '15', end_pos: '11' },
    { id_race: 19, id_driver: 18, id_driver_team: 7, start_pos: '16', end_pos: '12' },
    { id_race: 19, id_driver: 8, id_driver_team: 3, start_pos: '18', end_pos: '13' },
    { id_race: 19, id_driver: 10, id_driver_team: 2, start_pos: '13', end_pos: '14' },
    { id_race: 19, id_driver: 14, id_driver_team: 2, start_pos: '12', end_pos: '15' },
    { id_race: 19, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '16' },
    { id_race: 19, id_driver: 21, id_driver_team: 9, start_pos: '14', end_pos: '17' },
    { id_race: 19, id_driver: 3, id_driver_team: 5, start_pos: '19', end_pos: 'OUT' },
    { id_race: 19, id_driver: 12, id_driver_team: 6, start_pos: '10', end_pos: 'OUT' },
    { id_race: 19, id_driver: 11, id_driver_team: 10, start_pos: '8', end_pos: 'OUT' },
    { id_race: 20, id_driver: 20, id_driver_team: 8, start_pos: '3', end_pos: '1' },
    { id_race: 20, id_driver: 4, id_driver_team: 4, start_pos: '6', end_pos: '2' },
    { id_race: 20, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '3' },
    { id_race: 20, id_driver: 5, id_driver_team: 1, start_pos: '2', end_pos: '4' },
    { id_race: 20, id_driver: 1, id_driver_team: 6, start_pos: '17', end_pos: '5' },
    { id_race: 20, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: '6' },
    { id_race: 20, id_driver: 21, id_driver_team: 9, start_pos: '4', end_pos: '7' },
    { id_race: 20, id_driver: 12, id_driver_team: 6, start_pos: '7', end_pos: '8' },
    { id_race: 20, id_driver: 17, id_driver_team: 7, start_pos: '14', end_pos: '9' },
    { id_race: 20, id_driver: 11, id_driver_team: 10, start_pos: '15', end_pos: '10' },
    { id_race: 20, id_driver: 13, id_driver_team: 10, start_pos: '11', end_pos: '11' },
    { id_race: 20, id_driver: 15, id_driver_team: 9, start_pos: '18', end_pos: '12' },
    { id_race: 20, id_driver: 8, id_driver_team: 3, start_pos: '12', end_pos: '13' },
    { id_race: 20, id_driver: 14, id_driver_team: 2, start_pos: '10', end_pos: '14' },
    { id_race: 20, id_driver: 10, id_driver_team: 2, start_pos: '9', end_pos: '15' },
    { id_race: 20, id_driver: 18, id_driver_team: 7, start_pos: '19', end_pos: '16' },
    { id_race: 20, id_driver: 6, id_driver_team: 5, start_pos: '20', end_pos: '17' },
    { id_race: 20, id_driver: 3, id_driver_team: 5, start_pos: '13', end_pos: 'OUT' },
    { id_race: 20, id_driver: 16, id_driver_team: 3, start_pos: '16', end_pos: 'OUT' },
    { id_race: 20, id_driver: 2, id_driver_team: 8, start_pos: '5', end_pos: 'OUT' },
    { id_race: 21, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 21, id_driver: 1, id_driver_team: 6, start_pos: '6', end_pos: '2' },
    { id_race: 21, id_driver: 3, id_driver_team: 5, start_pos: '4', end_pos: '3' },
    { id_race: 21, id_driver: 2, id_driver_team: 8, start_pos: '9', end_pos: '4' },
    { id_race: 21, id_driver: 6, id_driver_team: 5, start_pos: '3', end_pos: '5' },
    { id_race: 21, id_driver: 5, id_driver_team: 1, start_pos: '7', end_pos: '6' },
    { id_race: 21, id_driver: 13, id_driver_team: 10, start_pos: '15', end_pos: '7' },
    { id_race: 21, id_driver: 4, id_driver_team: 4, start_pos: '5', end_pos: '8' },
    { id_race: 21, id_driver: 15, id_driver_team: 9, start_pos: '16', end_pos: '9' },
    { id_race: 21, id_driver: 11, id_driver_team: 10, start_pos: '14', end_pos: '10' },
    { id_race: 21, id_driver: 18, id_driver_team: 7, start_pos: '19', end_pos: '11' },
    { id_race: 21, id_driver: 8, id_driver_team: 3, start_pos: '11', end_pos: '12' },
    { id_race: 21, id_driver: 21, id_driver_team: 9, start_pos: '17', end_pos: '13' },
    { id_race: 21, id_driver: 12, id_driver_team: 6, start_pos: '10', end_pos: '14' },
    { id_race: 21, id_driver: 7, id_driver_team: 4, start_pos: '8', end_pos: 'OUT' },
    { id_race: 21, id_driver: 10, id_driver_team: 2, start_pos: '18', end_pos: 'OUT' },
    { id_race: 21, id_driver: 14, id_driver_team: 2, start_pos: '20', end_pos: 'OUT' },
    { id_race: 21, id_driver: 16, id_driver_team: 3, start_pos: '12', end_pos: 'OUT' },
    { id_race: 21, id_driver: 17, id_driver_team: 7, start_pos: '13', end_pos: 'OUT' },
    { id_race: 21, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: 'OUT' },
    { id_race: 22, id_driver: 20, id_driver_team: 8, start_pos: '2', end_pos: '1' },
    { id_race: 22, id_driver: 9, id_driver_team: 1, start_pos: '1', end_pos: '2' },
    { id_race: 22, id_driver: 2, id_driver_team: 8, start_pos: '11', end_pos: '3' },
    { id_race: 22, id_driver: 11, id_driver_team: 10, start_pos: '16', end_pos: '4' },
    { id_race: 22, id_driver: 6, id_driver_team: 5, start_pos: '19', end_pos: '5' },
    { id_race: 22, id_driver: 5, id_driver_team: 1, start_pos: '12', end_pos: '6' },
    { id_race: 22, id_driver: 4, id_driver_team: 4, start_pos: '10', end_pos: '7' },
    { id_race: 22, id_driver: 7, id_driver_team: 4, start_pos: '3', end_pos: '8' },
    { id_race: 22, id_driver: 3, id_driver_team: 5, start_pos: '9', end_pos: '9' },
    { id_race: 22, id_driver: 12, id_driver_team: 6, start_pos: '18', end_pos: '10' },
    { id_race: 22, id_driver: 13, id_driver_team: 10, start_pos: '4', end_pos: '11' },
    { id_race: 22, id_driver: 17, id_driver_team: 7, start_pos: '5', end_pos: '12' },
    { id_race: 22, id_driver: 16, id_driver_team: 3, start_pos: '8', end_pos: '13' },
    { id_race: 22, id_driver: 21, id_driver_team: 9, start_pos: '14', end_pos: '14' },
    { id_race: 22, id_driver: 14, id_driver_team: 2, start_pos: '17', end_pos: '15' },
    { id_race: 22, id_driver: 18, id_driver_team: 7, start_pos: '6', end_pos: '16' },
    { id_race: 22, id_driver: 10, id_driver_team: 2, start_pos: '7', end_pos: '17' },
    { id_race: 22, id_driver: 15, id_driver_team: 9, start_pos: '20', end_pos: '18' },
    { id_race: 22, id_driver: 8, id_driver_team: 3, start_pos: '13', end_pos: '19' },
    { id_race: 22, id_driver: 1, id_driver_team: 6, start_pos: '15', end_pos: 'OUT' },
    { id_race: 23, id_driver: 20, id_driver_team: 8, start_pos: '1', end_pos: '1' },
    { id_race: 23, id_driver: 9, id_driver_team: 1, start_pos: '2', end_pos: '2' },
    { id_race: 23, id_driver: 7, id_driver_team: 4, start_pos: '4', end_pos: '3' },
    { id_race: 23, id_driver: 2, id_driver_team: 8, start_pos: '9', end_pos: '4' },
    { id_race: 23, id_driver: 1, id_driver_team: 6, start_pos: '5', end_pos: '5' },
    { id_race: 23, id_driver: 12, id_driver_team: 6, start_pos: '3', end_pos: '6' },
    { id_race: 23, id_driver: 3, id_driver_team: 5, start_pos: '7', end_pos: '7' },
    { id_race: 23, id_driver: 15, id_driver_team: 9, start_pos: '6', end_pos: '8' },
    { id_race: 23, id_driver: 4, id_driver_team: 4, start_pos: '11', end_pos: '9' },
    { id_race: 23, id_driver: 6, id_driver_team: 5, start_pos: '13', end_pos: '10' },
    { id_race: 23, id_driver: 21, id_driver_team: 9, start_pos: '15', end_pos: '11' },
    { id_race: 23, id_driver: 11, id_driver_team: 10, start_pos: '12', end_pos: '12' },
    { id_race: 23, id_driver: 13, id_driver_team: 10, start_pos: '10', end_pos: '13' },
    { id_race: 23, id_driver: 17, id_driver_team: 7, start_pos: '14', end_pos: '14' },
    { id_race: 23, id_driver: 8, id_driver_team: 3, start_pos: '8', end_pos: '15' },
    { id_race: 23, id_driver: 18, id_driver_team: 7, start_pos: '20', end_pos: '16' },
    { id_race: 23, id_driver: 14, id_driver_team: 2, start_pos: '19', end_pos: '17' },
    { id_race: 23, id_driver: 5, id_driver_team: 1, start_pos: '16', end_pos: '18' },
    { id_race: 23, id_driver: 10, id_driver_team: 2, start_pos: '18', end_pos: '19' },
    { id_race: 23, id_driver: 16, id_driver_team: 3, start_pos: '17', end_pos: '20' },
];


